kiwitcms/Kiwi

requirements/mysql.txt, tcms/core/db.py
mysqlclient is the recommended DB API driver for Django:
https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-db-api-drivers
=> Use mysqlclient instead of MySQL-python. Fixes #14

tcms/core/ajax.py
=> Make TestCase changelog display state changes using their names

requirements/base.txt, tcms/settings/common.py, tcms/urls.py, tcms/xmlrpc/admin.py, tcms/xmlrpc/apps.py, tcms/xmlrpc/decorators.py, tcms/xmlrpc/dispatcher.py, tcms/xmlrpc/migrations/0001_initial.py, tcms/xmlrpc/models.py, tcms/xmlrpc/urls.py, tcms/xmlrpc/views.py
- copy XML-RPC related code from Kobo
- drop the dependency
=> Drop dependency on Kobo. Fix #5

CHANGELOG.rst, tcms/templates/plan/get_cases.html, tcms/templates/plan/plan_runs_part.html, tcms/templates/run/clone.html, tcms/templates/run/clone_multiple.html, tcms/templates/run/get.html, tcms/templates/run/new.html, tcms/testplans/urls/plan_urls.py, tcms/testruns/models.py, tcms/testruns/tests.py, tcms/testruns/urls/run_urls.py, tcms/testruns/views.py, tcms/tests/__init__.py
cherry-pick upstream #209 and more removals for reversal by dotted path
=> cherry-pick #209

tcms/core/tests/test_files.py, tcms/core/tests/test_views.py, tcms/core/utils/__init__.py, tcms/management/tests.py, tcms/templates/run/all.html, tcms/templates/run/common/json_runs.txt, tcms/templates/run/get_cc.html, tcms/testcases/tests.py, tcms/testplans/tests.py, tcms/testruns/models.py, tcms/testruns/tests.py, tcms/testruns/urls/run_urls.py, tcms/testruns/urls/runs_urls.py, tcms/testruns/views.py, tcms/tests/__init__.py, tcms/urls.py, tcms/xmlrpc/tests/test_testplan.py
Replacing deprecated `request.REQUEST` with `request.GET` or `request.POST`.
=> Upstream PRs 210, 211, 212, 213

tcms/core/files.py, tcms/core/models/fields.py, tcms/xmlrpc/serializer.py
This will facilitate migration to Django 1.10
=> Custom DB fields updates & bug fixes

tcms/static/js/testplan_actions.js, tcms/testplans/tests.py, tcms/testplans/views.py
serializers.serialize(extras) keyword is not supported
(may have never been) so we construct a list of dict values based
on the query results and return it as a JsonResponse
=> Fix a traceback when showing Plan -> Tree View

tcms/testplans/tests.py, tcms/testplans/views.py
=> Use correct permission names when editting Test Plan ENV Group

docs/source/contribution.rst, docs/source/index.rst, docs/source/installing_docker.rst, docs/source/set_dev_env.rst
@GodfatherThe this PR updates the docs for the issues you described in #89. Can you take a look and tell me if it looks OK to you? Thanks!
=> Update documentation for Docker and local devel environment

.gitignore, docs/Makefile, tcms/management/models.py, tcms/testcases/models.py, tcms/testplans/models.py, tcms/testruns/models.py, tcms/xmlrpc/api/auth.py, tcms/xmlrpc/api/build.py, tcms/xmlrpc/api/env.py, tcms_api/__init__.py, tcms_api/xmlrpc.py
I've taken to update the XML-RPC documentation bundled with the code because it is used to generate the HTML on Read The Docs. This is a small piece but already looking nice.
=> Various updates, mostly documentation

requirements/base.txt
Related to
https://github.com/pycontribs/jira/issues/501
=> Use jira 1.0.10. Fixes #195

tcms/core/ajax.py, tcms/core/tests/test_ajax.py
After the changes made in #193 , the front-end is no longer sending requests with multiple runs/cases/plans, so the `tag` method in `ajax.py` can be simplified. This would make the code a lot cleaner and would also remove the need for the multiple error handling mechanisms that were involved before. The places where an error could occur are a lot less now, and should one occur we would want to send it to the front-end, not catch it blindly.
=> Refactored ajax.py tag method to work with only one object

.gitignore
`.idea/` is a directory, created by JetBrains IDEs for workspace settings, preferences, etc.
=> Added .idea/ to .gitignore

docs/source/configuration.rst, tcms/auth/test_backend.py, tcms/core/contrib/auth/backends.py, tcms/templates/run/edit.html
Separating authentication backends out of this repository so we can test them independently and provide the blueprints for other auth backends.
=> Move auth backends out of this repo

tcms/core/ajax.py, tcms/core/tests/test_ajax.py
Added separate tests for both classes
Removed template_name parameter from tag method in ajax.py
Updated ajax module doc-string
=> Refactored TagActions and TagObjects to be outer classes. Fixes #257

requirements/base.txt
https://docs.djangoproject.com/en/2.0/releases/2.0.4/
Expected release: 2nd April
=> Upgrade to Django 2.0.4

tcms/management/tests.py, tcms/management/views.py, tcms/search/__init__.py, tcms/search/forms.py, tcms/testplans/urls/plan_urls.py
Just a look at the the `CodeCov` report shows that `tcms.management.views` was missing tests for two small branches - this PR adds them. 
Also, refactored list comprehension in two modules and minor pylint fixes in two other modules.
=> Pylint fixes, list comprehensions and tests

tcms/report/data.py, tcms/report/views.py
Separate PR for the many changes in `tcms.report.data`
=> Fixed pylint issues in module tcms.report.data

tcms/testplans/forms.py, tcms/testplans/views.py
This PR turned out bigger than I intended because of the many issues in `tcms.report.data`. Mostly list comprehensions, and methods that could be static among other things. 
Please note than other than adding `@staticmethod` to these methods I have also moved them to the bottom of their class.
=> Pylint fixes for two modules

tcms/core/utils/__init__.py, tcms/core/utils/raw_sql.py
Small pylint fixes for two modules + leftover from #331
=> Pylint fixes

tcms/xmlrpc/tests/test_category.py, tcms/xmlrpc/tests/test_testcase.py, tcms/xmlrpc/tests/test_utils.py, tcms/xmlrpc/tests/test_version.py, tcms/xmlrpc/utils.py
Small fixes for `tcms.xmlrpc` modules
=> Pylint fixes for xmlrpc.

tcms/report/views.py, tcms/testruns/models.py, tcms/testruns/views.py
Small fixes for some of the issues in `tcms.testruns.models`
=> Fixed some pylint issues in module tcms.testruns.models

tcms/templates/plan/get.html
It was just a missed slash so it became so ugly few months ago!
=> fix ugly strong everywhere

tcms/core/contrib/auth/admin.py, tcms/core/models/base.py, tcms/core/utils/mailto.py, tcms/testcases/models.py
`tcms.core.models.base`
`tcms.core.utils.mailto`
`tcms.core.contrib.auth.admin`
=> Small pylint fixes for three modules

tcms/core/ajax.py
This should resolve all issues in `tcms.core.ajax` for now
=> Fixed pylint issues in tcms.core.ajax

tcms/static/js/testplan_actions.js, tcms/templates/plan/get.html
Instead of weird out-of-style text link use proper button with common look&feel
=> Use button for deleting test plan

tcms/core/views.py, tcms/static/js/testplan_actions.js, tcms/xmlrpc/api/__init__.py, tcms/xmlrpc/api/testcaserun.py, tcms/xmlrpc/api/testrun.py, tcms/xmlrpc/tests/test_testrun.py
=> Misc update - API, docs, dashboard & JavaScript

tcms/testruns/views.py
Field TestCase.default_tester cannot be both deferred and traversed
using select_related at the same time
=> Fix InvalidQuery, refs #346

.travis.yml, Dockerfile, Makefile, tests/runner.sh, tests/test_docker.sh
This should fail. The fix is in #626 .
=> Add tests for restarting docker container

tcms/xmlrpc/api/testcase.py
Initially requested on SO:
https://stackoverflow.com/questions/53844380/
=> [api] new method TestCase.remove()

kiwi_lint/__init__.py, kiwi_lint/missing_permissions.py, kiwi_lint/nested_definition.py
=> 2 new linters to help avoid common pitfalls

kiwi_lint/auth_user.py, tcms/xmlrpc/api/user.py
because this makes the application less customizeable.
CC @ivo0126 , @asankov - FYI
=> [linter] Warn about importing the stock User model

.travis.yml, Makefile, tcms/testplans/models.py
originally reported in:
https://stackoverflow.com/questions/54177838/
Also see:
https://github.com/treyhunner/django-simple-history/issues/512
=> Test for missing migrations

tcms/testcases/static/testcases/js/search.js, tcms/testcases/templates/testcases/search.html
=> Show TestCase components in TestCase Search page

tcms/testcases/templates/testcases/mutable.html
there were quite a few typos and missing pieces left over when
converting the template!
@asankov FYI, this should have been fixed together with #730.
=> Fix error handling tags, leftover from #730

tcms/testcases/static/testcases/js/search.js, tcms/testcases/templates/testcases/search.html
Refs #715, #123 
The logic for showing tags is basically the same as showing components since the relation is same. Thus I extracted the shared code into functions - `loadResources` and `getFromCache` and everything worked as expected
=> Show TestCase tag in TestCase search page

tcms/locale/de_DE/LC_MESSAGES/django.po, tcms/locale/en/LC_MESSAGES/django.po, tcms/locale/fr_FR/LC_MESSAGES/django.po, tcms/locale/sl_SI/LC_MESSAGES/django.po, tcms/locale/zh_CN/LC_MESSAGES/django.po, tcms/locale/zh_TW/LC_MESSAGES/django.po, tcms/static/js/jsonrpc.js, tcms/templates/datetimepicker_script.html, tcms/testcases/static/testcases/js/search.js, tcms/testcases/templates/testcases/search.html, tcms/testplans/static/testplans/js/search.js, tcms/testplans/templates/testplans/search.html, tcms/testruns/static/testruns/js/search.js, tcms/testruns/templates/testruns/mutable.html, tcms/testruns/templates/testruns/search.html, tcms/xmlrpc/api/testcase.py, tcms/xmlrpc/api/testplan.py
=> Visual updates for search pages + minor performance improvement

tcms/templates/case/attachment.html, tcms/templates/case/clone.html, tcms/templates/case/clone_select_plan.html, tcms/templates/case/edit.html, tcms/templates/case/get_details.html, tcms/templates/case/get_details_case_run.html, tcms/templates/case/printable.html, tcms/templates/management/get_tag.html, tcms/templates/navbar.html, tcms/templates/plan/attachment.html, tcms/templates/plan/cases_rows.html, tcms/templates/plan/clone.html, tcms/templates/plan/get.html, tcms/templates/plan/get_attachments.html, tcms/templates/plan/get_cases.html, tcms/templates/plan/preview.html, tcms/templates/plan/search_case.html, tcms/templates/registration/login.html, tcms/templates/registration/password_reset_complete.html, tcms/templates/registration/password_reset_confirm.html, tcms/templates/run/assign_case.html, tcms/templates/run/get.html, tcms/templates/run/get_case_runs.html, tcms/templates/run/get_cc.html, tcms/templates/run/report.html, tcms/templates/run/status_statistics.html, tcms/templates/run/table_caseruns.html
=> Translatable template apps

tcms/locale/de_DE/LC_MESSAGES/django.po, tcms/locale/en/LC_MESSAGES/django.po, tcms/locale/fr_FR/LC_MESSAGES/django.po, tcms/locale/sl_SI/LC_MESSAGES/django.po, tcms/locale/zh_CN/LC_MESSAGES/django.po, tcms/locale/zh_TW/LC_MESSAGES/django.po, tcms/testcases/templates/testcases/get.html, tcms/testcases/templates/testcases/search.html
actually show the user who tested this TC
=> Remove hard-coded value from testcases/get.html. Fixes #765

Makefile, tcms/kiwi_auth/test_admin.py, tcms/kiwi_auth/tests.py, tcms/locale/de_DE/LC_MESSAGES/django.po, tcms/locale/en/LC_MESSAGES/django.po, tcms/locale/fr_FR/LC_MESSAGES/django.po, tcms/locale/sl_SI/LC_MESSAGES/django.po, tcms/locale/zh_CN/LC_MESSAGES/django.po, tcms/locale/zh_TW/LC_MESSAGES/django.po, tcms/testruns/tests/test_models.py
=> Localization & translation updates

.travis.yml, Makefile, docs/source/modules/tcms.core.rst, docs/source/modules/tcms.core.serializer.rst, tcms/core/serializer.py, tcms/settings/common.py, tcms/settings/test/__init__.py, tcms/xmlrpc/serializer.py, tcms/xmlrpc/tests/test_testcaserun.py, tcms/xmlrpc/tests/test_testrun.py, tcms/xmlrpc/tests/test_version.py
we can now enable localized testing in Travis CI which helps identify more issues
=> More localization fixes

tcms/testcases/forms.py
=> Turn on TestCase notifications by default

CHANGELOG.rst, tcms_api/setup.py, tcms_api/tcms_api/plugin_helpers.py
=> [tcms-api] expose plugin_helpers.Backend.add_comment()

docs/source/installing_docker.rst
Documentation of the configuration for using an alternative to nginx.
=> Reverse Proxy configuration for HAProxy.

tcms/locale/de_DE/LC_MESSAGES/django.po, tcms/locale/en/LC_MESSAGES/django.po, tcms/locale/fr_FR/LC_MESSAGES/django.po, tcms/locale/sl_SI/LC_MESSAGES/django.po, tcms/locale/zh_CN/LC_MESSAGES/django.po, tcms/locale/zh_TW/LC_MESSAGES/django.po, tcms/testcases/templates/testcases/mutable.html
Changed English base translation from Requirments -> Requirements
Not sure if base translation will also automatically update the translation key string in translation .po files or I need to change them manually?
=> mutable.html - Changed English base translation from Requirments -> Requirements

tcms/static/js/testplan_actions.js
jQ hasn't instance of DataTable
=> use instance of jquery which has instance of DataTable object

tcms/templates/attachments/delete_link.html
It is my first contribution. That is why I decided to get something small.
=> Prompt user on attachment deletion. Fixes #867

Dockerfile, docker-compose.postgres, tcms/settings/common.py, tests/test_docker.sh
All of these make it possible to switch to PostgreSQL as the DB backend if one desires to do so.
=> Changes related to using PostgreSQL as DB backend

docs/source/admin.rst
IR -> IP
exmplained -> explained
=> [docs] Admin.rst - fixed two typos

tcms/locale/cs_CZ/LC_MESSAGES/django.po, tcms/locale/de_DE/LC_MESSAGES/django.po, tcms/locale/en/LC_MESSAGES/django.po, tcms/locale/fr_FR/LC_MESSAGES/django.po, tcms/locale/ru_RU/LC_MESSAGES/django.po, tcms/locale/sl_SI/LC_MESSAGES/django.po, tcms/locale/zh_CN/LC_MESSAGES/django.po, tcms/locale/zh_TW/LC_MESSAGES/django.po, tcms/telemetry/api.py, tcms/telemetry/static/telemetry/css/testing/breakdown.css, tcms/telemetry/static/telemetry/js/testing/breakdown.js, tcms/telemetry/templates/telemetry/testing/breakdown.html
- Add date filter for test cases
- Automated/manual bar legend now contains the values
- Prioties and categories chart now show confirmed vs not confirmed test cases count
=> Fix leftovers for Telemetry - Testcase Breakdown

kiwi_lint/__init__.py, kiwi_lint/one_to_one_field.py
https://github.com/kiwitcms/Kiwi/pull/950 rebased
=> Pr950 rebased and squashed

.travis.yml, Makefile
Fixed path to bandit site packages
=> Bandit path fix

tcms/kiwi_auth/views.py
Disable @permission_required decorator check in pylint for 2 views
=> Disable pylint checks for 2 views

tcms/telemetry/static/telemetry/js/testing/breakdown.js, tcms/telemetry/templates/telemetry/testing/breakdown.html
to use methods from utils.js
Also, rename some of the ids in the template to match those expected by said methods
=> Refactor testing/breakdown.js

tcms/core/views.py, tcms/kiwi_auth/views.py, tcms/telemetry/views.py, tcms/testcases/views.py, tcms/testplans/views.py, tcms/testruns/views.py
Disable pylint message for unnecessary checks. Refs kiwitcms #171
=> Decorator fix

tcms/settings/common.py, tcms/telemetry/api.py, tcms/telemetry/static/telemetry/js/testing/breakdown.js, tcms/telemetry/static/telemetry/js/testing/execution-trends.js, tcms/telemetry/static/telemetry/js/testing/utils.js, tcms/telemetry/templates/telemetry/testing/execution-trends.html, tcms/telemetry/urls.py, tcms/telemetry/views.py, tcms/testruns/models.py
This adds `TestingExecutionTrendsView`. 
Currently, the only functionallity is the chart. While you are reviewing that I will work on implementing `Passing Rate Summary`.
=> Add TestingExecutionTrendsView

tcms/telemetry/static/telemetry/js/testing/breakdown.js, tcms/telemetry/static/telemetry/js/testing/execution-trends.js
Fix some of the leftovers from #992
=> Test execution trends leftovers

docs/source/installing_docker.rst, etc/kiwi-httpd.conf, httpd-foreground
=> Provide OptIn parameter to not enforce HTTPS fixes #1036

.travis.yml
makes web output easier to parse
=> [ci] Rearrange Travis CI env variables

tcms/testcases/templates/testcases/clone.html, tcms/testcases/templates/testcases/mutable.html, tcms/testcases/templates/testcases/search.html, tcms/testplans/templates/testplans/clone.html, tcms/testplans/templates/testplans/mutable.html, tcms/testplans/templates/testplans/search.html, tcms/testruns/templates/testruns/mutable.html, tcms/testruns/templates/testruns/search.html
When add new test case the save button is stucked to the bottom of the web page.
=> Add breathing room around save button

docs/source/modules/tcms.issuetracker.redmine_integration.rst, docs/source/modules/tcms.issuetracker.rst, requirements/base.txt, tcms/issuetracker/redmine_integration.py, tcms/issuetracker/types.py
Tested at Redmine v3.4.x and v4.x.
=> Add support for Redmine issue tracker

tcms/testruns/views.py
=> Mark string as translatable

tcms/settings/common.py, tcms/telemetry/api.py, tcms/telemetry/static/telemetry/js/testing/test-case-health.js, tcms/telemetry/templates/telemetry/testing/test-case-health.html, tcms/telemetry/urls.py, tcms/telemetry/views.py
=> Implement FE for Test case health

tcms/static/js/testrun_actions.js, tcms/static/style/base.css, tcms/templates/run/get_case_runs.html
=> Testexecution bug and hyperlinks enhancement

tcms/static/js/testrun_actions.js
Validation added in javascript. Will only allow http(s)://host.domain urls.
=> Fix bug hyperlink validation

tcms/core/ajax.py, tcms/core/tests/test_admin.py, tcms/core/tests/test_ajax.py, tcms/core/tests/test_views.py, tcms/testruns/views.py
Add __init__.py in tcms/core/tests and fix all failing tests
=> Fix core tests

tcms/core/contrib/comments/utils.py, tcms/core/helpers/comments.py, tcms/core/tests/test_helpers.py, tcms/rpc/api/testexecution.py, tcms/rpc/tests/test_testexecution.py, tcms/static/js/testrun_actions.js, tcms/testcases/views.py
=> Updates around the duplicate comment methods.

tcms/core/models/__init__.py, tcms/rpc/api/forms/testcase.py, tcms/rpc/api/forms/testplan.py, tcms/rpc/api/forms/testrun.py, tcms/rpc/api/testcase.py, tcms/rpc/api/testexecution.py, tcms/rpc/api/testrun.py, tcms/rpc/api/user.py, tcms/rpc/forms.py, tcms/rpc/serializer.py, tcms/rpc/tests/test_serializer.py
Depends on #1217 
Review after that is merged
=> Rename XMLRPC forms and other classes

tcms/testruns/tests/test_permissions.py, tcms/testruns/tests/test_views.py
Add tests for CreateTestRun view using new PermissionsTestCase class.
=> Tests for CreateTestRun views refractored

.travis.yml
this will schedule all jobs in parallel and not wait between them
which should reduce the overall feedback time on pull requests.
=> Remove Travis CI stages

.gitignore
This is a directory that the VSCode editor creates
=> Add `.vscode/` to `.gitignore`

tcms/telemetry/static/telemetry/js/testing/test-case-health.js
similar to 010783b587df814204fe23c10f6b09fb3e5b6614
will show all data in the corner case, where the cases are deleted
from TestPlan.
CC @asankov
=> Fix TestCase health telemetry query

tcms/testplans/tests/test_permissions.py, tcms/testplans/tests/tests.py, tcms/testplans/views.py
WIP - please look if the tests are good or I need to refactor with use of PermissionsTestCase. If they are good, I will finish the case without permissions.
=> Add permission to testplans DeleteCasesView

tcms/core/views.py, tcms/testplans/tests/test_permissions.py, tcms/testplans/tests/tests.py, tcms/testplans/views.py
Add permission to testplans ReorderCasesView
=> Add permission to testplans ReorderCasesView

tcms/testruns/tests/test_permissions.py, tcms/testruns/tests/test_views.py
Refractor permission tests for GetTestRunView
=> Refractor permission tests for GetTestRunView

tcms/kiwi_auth/urls.py, tcms/kiwi_auth/views.py, tcms/settings/common.py
=> Refactor register form view to use class view

tcms/testcases/fields.py, tcms/testcases/forms.py, tcms/testcases/models.py, tcms/testcases/templates/testcases/mutable.html, tcms/testcases/tests/test_views.py, tcms/testcases/urls/case_urls.py, tcms/testcases/views.py
=> Refactor test case views (New, Edit) to generic views

tcms/bugs/views.py, tcms/core/response.py, tcms/core/tests/test_views.py, tcms/rpc/tests/test_serializer.py, tcms/settings/common.py, tcms/settings/test/__init__.py, tcms/telemetry/tests/plugin/urls.py, tcms/telemetry/tests/plugin/views.py, tcms/testcases/views.py, tcms/testplans/views.py, tcms/testruns/tests/test_views.py, tcms/tests/__init__.py
=> Happy New Year pylint

tcms/rpc/api/forms/testcase.py, tcms/rpc/api/testcase.py, tcms/rpc/tests/test_testcase.py, tcms/testcases/forms.py, tcms/testcases/views.py
=> Updates around TestCase forms and API methods

tcms/core/tests/test_ajax.py, tcms/kiwi_auth/urls.py, tcms/kiwi_auth/views.py, tcms/testcases/tests/test_views.py, tcms/testplans/tests/test_permissions.py, tcms/testplans/tests/tests.py, tcms/testruns/tests/test_update_caserun_status_view.py, tcms/testruns/tests/test_views.py, tcms/tests/__init__.py
=> Some updates around tests & CBV

tcms/telemetry/templates/telemetry/testing/breakdown.html, tcms/telemetry/templates/telemetry/testing/execution-trends.html, tcms/telemetry/templates/telemetry/testing/status-matrix.html, tcms/telemetry/templates/telemetry/testing/test-case-health.html, tcms/templates/telemetry/include/filters.html
extract that into a new template, which is then imported into the different telemetry views
=> Extract common filters HTML used in telemetry templates

tcms/testruns/tests/test_admin.py
new test_admin_add_view function has been added
=> test_admin.py file was created

tcms/static/js/testrun_actions.js, tcms/templates/run/status_progress.html, tcms/templates/run/status_statistics.html
@atodorov I left two TODOs in the code. I would like to hear your opinion on them:
do we have this ID loaded somewhere, where I can use it and I am just not seeing it?
```javascript
// TODO: better way to do this
const testRunId = window.location.pathname.split('/')[2]
```
IMO this data structure is good enough for the purpose I am using it, but if you can think of a more elegant solution I will apply it
```javascript
// TODO: better solution
executionStatuses.forEach(s => statusCount[s.name] = { count: 0, id: s.id })
```
=> Update status bar dinamically 

tcms/telemetry/static/telemetry/js/testing/execution-trends.js
=> Handle the case where there are no executions

tcms/telemetry/static/telemetry/css/testing/test-case-health.css, tcms/telemetry/static/telemetry/js/testing/test-case-health.js, tcms/telemetry/templates/telemetry/testing/test-case-health.html
=> Add visual representation of failures

tcms/templates/plan/get_cases.html
Sentry #KIWI-TCMS-A6
https://sentry.io/organizations/open-technologies-bulgaria-ltd/issues/1519809326/
=> Fix field name leading to crash when sorting TC in TP

tcms/testcases/static/testcases/js/get.js, tcms/testcases/templates/testcases/get.html
TestPlan can be selected with the following selectors:
- TP-XYZ - where XYZ are integer numbers representing ID
- XYZ - where XYZ are integer numbers representing ID
- ABC - where ABC is a string found anywhere inside plan's name
All searches are case insensitive!
=> Allow adding TestPlan to TestCase via UI. Fixes #1021

docs/source/installing_docker.rst, docs/source/modules/tcms.utils.rst, docs/source/modules/tcms.utils.settings.rst, tcms/settings/local_settings_test/installed_apps_update.py, tcms/settings/local_settings_test/marketplace_secret.py, tcms/settings/local_settings_test/version_update.py, tcms/settings/product.py, tcms/utils/settings.py, tcms/utils/tests/test_local_settings_dir.py
product.py now respects:
- local_settings.py
- local_settings_dir/*.py
=> Make it possible to provide override settings in a directory

tcms/testplans/static/testplans/js/get.js, tcms/testplans/templates/testplans/get.html
Add testcases summary details. Reuse design from testcase page.
=> [WIP]Testcase summary details

tcms/testcases/static/testcases/js/search.js, tcms/testcases/templates/testcases/search.html
=> Add text to test case search filter. Closes #1209

tcms/bugs/tests/test_models.py, tcms/signals.py
Fix for #1510 
If this fix is sufficient, no need for the bounty :)
=> Fix #1510 - pylint .format errors.

tcms/bugs/templates/bugs/get.html, tcms/bugs/tests/test_views.py, tcms/bugs/views.py
Fix for #1152 
I have mixed up the commit history at #1496 and open a new PR to be cleaner.
@asankov Can you please go on with this PR?
-- Applied the latest review changes.
=> Feature - Issue 1152 - Reopening closed bugs.

tcms/rpc/api/forms/__init__.py, tcms/rpc/api/forms/testrun.py, tcms/rpc/api/testrun.py, tcms/rpc/tests/test_testrun.py
I am not sure of the implications of this, and what is the right way to test it. Please advice.
=> Make `testruns.UpdateForm` inherit from `ModelForm`

tcms/testruns/templates/testruns/get.html
I wonder if this can a bit bigger, maybe `col-md-8`
=> Add attachments to Test Run page

tcms/telemetry/api.py, tcms/telemetry/static/telemetry/js/testing/execution-trends.js, tcms/telemetry/templates/telemetry/testing/execution-trends.html
in the tooltip of Execution trends
=> Show TOTAL executions in the tooltip of Execution trends

.github/workflows/lint.yml, .travis.yml, requirements/readthedocs.txt
closes #1550 
* add bandit job to Github workflows
* remove bandit job from Travis CI
* remove bandit package from requirements
=> Add bandit job to Github workflows

tcms/testruns/static/testruns/js/get.js, tcms/testruns/templates/testruns/get.html
=> Initial touches on Test executions table

tcms/testcases/tests/test_admin.py
+ TestCaseAdmin.add_view()
+ TestCaseAdmin.change_view()
=> Tests for TestCaseAdmin

tcms/core/response.py
root cause is that settings are cached and after override
MENU_ITEMS is modified. In case of intermediary failures it was
not restored and other pages were showing bogus menu items.
This seems to resolve the problem although it's now very hard to
reproduce this problem reliably, hence no actual test.
=> Try harder to restore original settings. Fixes #991

tcms/bugs/tests/test_admin.py
+ BugAdmin.add_view()
+ BugAdmin.change_view()
=>  Tests for BugAdmin Fixes #1596

.github/workflows/sanity.yml, .travis.yml
Closes #1554
* add build-for-pypi job to GitHub workflow
* remove build-for-pypi job from Travis CI
=> add build-for-pypi to GitHub workflow

tcms/core/tests/test_forms.py
Added Unit Tests for tcms.core.forms.fields - UserField
Please let me know if any explanatory comments are needed in the test code.
=> Automated tests for missing coverage tcms.core.forms.fields - Fix #1629

tcms/testplans/static/testplans/js/get.js, tcms/testplans/templates/testplans/get.html
Add dom manipulations in the callbacks of the rpc calls
=> Update the dom when testcase property is changed

tcms/locale/zh_CN/LC_MESSAGES/django.po
Split from #1664 b/c trying to keep track of language contributions.
Originally contributed by Sourav Singh (souravsingh)
=> New translations django.po (Chinese Simplified)

tcms/locale/ko_KR/LC_MESSAGES/django.po
Split from https://github.com/kiwitcms/Kiwi/pull/1664, original contribution by Sourav Singh (souravsingh)
=> New translations django.po (Korean)

tcms/static/js/testrun_actions.js
cc @asankov, @rsasov - this needs to go into refactor_testrun_ui branch as well b/c the current patch is incomplete.
=> Replace all &amp; in URLs received via API. Better fix for #1533

tcms/bugs/tests/test_permissions.py, tcms/rpc/tests/test_testexecution.py, tcms/rpc/tests/test_version.py, tcms/rpc/tests/utils.py, tcms/testplans/tests/test_permissions.py, tcms/tests/__init__.py
@rsasov, @mfonism FYI,  see how `TestVersionCreatePermissions` uses the new base class for testing.
=> Api permissions testcase

tcms/testplans/tests/test_views.py, tcms/testplans/views.py
Added tests for tcms.testplans.views.Edit.
=> Test for tcms.testplans.views.Edit. Refs #1617

tcms/testplans/tests/test_views.py
=> tests: Small improvements onto #1677. Closes #1617

kiwi_lint/__init__.py, kiwi_lint/forms.py
Resolves #738. Add new linter to check for label arguments in form field classes.
=> Add new linter to check for label arguments

.github/workflows/sanity.yml, .travis.yml
Resolves #1553. Migrates 'test-for-missing-migrations' from Travis CI to GH WF
=> Migrates 'test-for-missing-migrations' from Travis CI to GH WF

docs/source/plugins/automation-frameworks.rst
Resolves #693. Update list of available Automation Framework plugins in docs
=> Update list of available Automation Framework plugins

.github/workflows/testing.yml, tcms/bugs/migrations/0002_add_permissions.py, tcms/core/middleware.py, tcms/core/tests/test_middleware.py, tcms/settings/common.py
Resolves #1696. Add middlware to warn for unapplied migrations
=> Add middleware to warn for unapplied migrations

tcms/issuetracker/base.py, tcms/issuetracker/bugzilla_integration.py, tcms/issuetracker/tests/test_bugzilla.py, tcms/issuetracker/tests/test_github.py, tcms/issuetracker/tests/test_gitlab_ee.py, tcms/issuetracker/tests/test_jira.py, tcms/issuetracker/tests/test_kiwitcms.py, tcms/issuetracker/tests/test_redmine.py, tcms/rpc/api/bug.py, tcms/rpc/api/testexecution.py, tcms/rpc/api/utils.py
Refs https://github.com/kiwitcms/github-app/issues/25 - will need
information about the current user & tenant in order to figure out
the individual GitHub App installation that is going to be used for
RPC requests.
=> Pass request to base.IssueTrackerType()

tcms/bugs/tests/test_api.py
This PR adds tests for the `remove()` api method in `tcms/bugs/api.py` as per #1597
=> Add tests for API method tcms.bugs.api.remove()

.github/workflows/sanity.yml, docs/source/modules/tcms.core.management.commands.migrations_order.rst, docs/source/modules/tcms.core.management.commands.rst, tcms/core/management/commands/migrations_order.py, tests/migrations-rollback
=> Migration rollback testing

tcms/testplans/static/testplans/js/get.js, tcms/testplans/templates/testplans/get.html, tcms/testplans/views.py
Im unable to find bulk selector html/style. Any suggestions?
=> Draft: toolbar for tc in tp page

tcms/rpc/tests/test_testplan.py
=> add test for tcms.rpc.api.testplan #1627

tcms/bugs/apps.py
should have been added in 77c1e1ae but it wasn't
=> Delete comments when Bug is removed. Refs #1028

tcms/templates/plan/cases_rows.html, tcms/templates/plan/get.html, tcms/templates/plan/get_cases.html, tcms/templates/run/status_statistics.html, tcms/templates/run/table_executions.html
these have been deprecated so replace them with a simple if tag
=> Replace ifequal/ifnotequal template tags

tcms/settings/common.py, tcms/testcases/migrations/0006_merge_text_field_into_testcase_model.py, tcms/testcases/migrations/0010_remove_bug.py, tcms/testcases/migrations/0011_trim_bugsystem_fields.py
This patch makes the location of temporary files in migrations platform dependent
=> Fix location of temp files in migrations

tcms/testruns/static/testruns/js/get.js, tcms/testruns/templates/testruns/get.html
on top of #1908 so that I can reuse the `selectedCheckboxes` function
=> Implement bulk change execution assignee

tcms/core/management/commands/migrations_order.py
=> Update signature for overriden class to match Django 3.1

tcms/testplans/views.py
=> Add Object permissions menu for TestPlan. Refs #1911

tcms/testruns/views.py
=> Add Object permissions menu. Refs #1911

tcms/testruns/static/testruns/js/get.js
in the `bulk-change-status` button handler
=> Add a comment on why we `return false`

tcms/rpc/api/testexecution.py, tcms/rpc/tests/test_testexecution.py
```
$ curl 'http://localhost:8000/json-rpc/' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:80.0) Gecko/20100101 Firefox/80.0' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Accept-Language: en-US,en;q=0.7,bg;q=0.3' --compressed -H 'Content-Type: application/json' -H 'X-Requested-With: XMLHttpRequest' -H 'Origin: http://localhost:8000' -H 'Connection: keep-alive' -H 'Referer: http://localhost:8000/runs/1/' -H 'Cookie: csrftoken=BbgrN3nhlYb2WBnAKoC2wLhYoX5jYI5uYUXbfE2dPqJsONerUKKujMzoP74lLjcT; token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyIjp7ImlkIjoiMSIsInVzZXJuYW1lIjoiYXNhbmtvdiIsImVtYWlsIjoiYXNhbmtvdiJ9LCJleHAiOjE1OTk0MjU1NjB9.SIM+Afy8Z06/ili3TYnue+JMXFqlrD4Ik59B/gQ4kU4=; djdt=hide; sessionid=rg9xh9nzswhy6azrd9oa3gnxlgzvxcc7; …
```
=> Add `TestExecution.get_comments` API

tcms/static/js/utils.js, tcms/testplans/static/testplans/js/get.js, tcms/testplans/templates/testplans/get.html
and related improvements in columns/menu order/filtering & sorting
=> Show testcase status column

tcms/testplans/static/testplans/js/get.js
DO NOT MERGE - it depends on bulk_actions branch
=> Apply utils animate

tests/gitlab_ee/initialize-data
hoping that IDs will restart from 1 so that issue creation
works
=> tests: Delete a GitLab project that is created automatically

tcms/testplans/static/testplans/js/get.js, tcms/testplans/templates/testplans/get.html
As we show all testcases without pagination I think that 1054 will not be an issue.
=> Add bulk clone for testcases. Ref #1054

docs/source/modules/tcms.rpc.api.markdown.rst, docs/source/modules/tcms.rpc.api.rst, tcms/rpc/api/markdown.py, tcms/settings/common.py, tcms/static/js/utils.js
which will be used by the FE to safely render markdown coming
from the backend!
=> Add Markdown.render() API method & front-end util functions

tcms/rpc/api/testcase.py, tcms/rpc/tests/test_testcase.py, tcms/static/js/utils.js, tcms/templates/include/comments_for_object_template.html, tcms/testplans/static/testplans/js/get.js, tcms/testplans/templates/testplans/get.html, tcms/testplans/views.py
Note: we're missing TestCase.comments() API  so the display portion isn't ready yet.
=> Testcase review comments

tcms/rpc/api/testcase.py, tcms/rpc/tests/test_testcase.py, tcms/static/js/utils.js, tcms/testplans/static/testplans/js/get.js
See the TODOs. I think I will change the API but not sure for the second one.
=> Initially load test cases by their sortkey

Makefile
so we can see what's happening in CI
CC @brymut
=> Convert find into a loop and print dir names before running pylint

tcms/utils/tests/test_assign_permissions.py
Test for tcms.utils.permissions.assign_default_group_permissions()
=> Test for assign_default_group_permissions()

tcms/rpc/tests/test_testrun.py
=> add test for tcms.rpc.api.testrun #1628

tcms/testcases/templates/testcases/clone.html, tcms/testcases/templates/testcases/mutable.html, tcms/testplans/templates/testplans/clone.html, tcms/testplans/templates/testplans/mutable.html, tcms/testplans/templates/testplans/search.html, tcms/testplans/tests/test_new_plan.py, tcms/testplans/tests/test_views.py
Changed the bootstrap swich : added data-on-text and data-off-text to the swiches.
=> Change of bootstrap switch

docs/source/installing_docker.rst, docs/source/modules/tcms.core.management.commands.initial_setup.rst, docs/source/modules/tcms.core.management.commands.rst, tcms/core/management/commands/initial_setup.py
=> Command line tool for initial setup

tcms/rpc/api/testcase.py, tcms/rpc/tests/test_testcase.py
=> Add test for tcms.rpc.api.testscase #1623

tcms/testruns/static/testruns/js/get.js, tcms/testruns/templates/testruns/get.html, tcms/testruns/tests/test_permissions.py, tcms/testruns/tests/test_views.py
Notes:
- bulk `Add comment` is now a button (will change to menu item)
but there doesn't seem to be any permission checks around these
buttons. Refs #716
- view tests will probably fail b/c the expected values have not
been adjusted yet
=> Unskip previously skipped tests

tcms/rpc/api/testplan.py
Disabled pylint to not show errors
=> Disable pylint

tcms/testruns/tests/test_views.py, tcms/testruns/views.py
because they share lots of functionality and we can avoid the
repetition.
=> Refactor CloneTestRunView to inherit from NewTestRunView

tcms/testruns/static/testruns/js/get.js
to be consistent with the other parts of the file and of the new JS ones
=> Reformat the file and remove semicolons

tcms/core/tests/test_views.py
Fix #1606 
Changes were inspired by https://docs.djangoproject.com/en/3.1/topics/http/views/#testing-custom-error-views
=> Add automated tests for tcms.core.views.server_error

tcms/testplans/tests/test_new_plan.py
=> [WIP] add test for tcms.testplans.views.NewTestPlanView.

tcms/testruns/static/testruns/js/get.js, tcms/testruns/templates/testruns/get.html, tcms/testruns/tests/test_permissions.py
=> Add bulk comment to TestRun page

tcms/testruns/static/testruns/js/get.js
e.g. filter by status from the URLs in progress card.
Notes:
- change a forEach loop to a for loop b/c we can't use
`continue` with forEach!
- the queries in renderAdditionalInformation() are overzealous
when the page is filterred by status and thus some elements from
`allExecutions` simply don't exist. Hence the `continue`
statement!
=> Filter TE rows if URL params present

tcms/locale/en/LC_MESSAGES/django.po, tcms/rpc/api/forms/testrun.py, tcms/rpc/api/testrun.py, tcms/testruns/static/testruns/js/get.js, tcms/testruns/templates/testruns/get.html
New API:
- TestRun.add_cc()
- TestRun.remove_cc()
=> Reimplement email CC for test run page.

tcms/tests/test_handlers.py
=> Fixes #1611 - Adds test for tcms.handlers

tcms/kiwi_auth/tests/test_profiles.py, tcms/kiwi_auth/tests/test_views.py
=> Add automated test for tcms.kiwi_auth.views

tcms/bugs/templates/bugs/get.html, tcms/bugs/templates/bugs/mutable.html, tcms/bugs/templates/bugs/search.html, tcms/core/middleware.py, tcms/settings/common.py, tcms/telemetry/templates/telemetry/include/filters.html, tcms/telemetry/templates/telemetry/testing/status-matrix.html, tcms/testcases/templates/testcases/clone.html, tcms/testcases/templates/testcases/mutable.html, tcms/testcases/templates/testcases/search.html, tcms/testplans/templates/testplans/search.html, tcms/testruns/templates/testruns/search.html
and add csrf_token in forms which were missing it.
=> Remove CsrfDisableMiddleware. Closes #297

tcms/settings/common.py
=> Remove kiwi.rpc log handler from LOGGING setting

tcms/rpc/api/testexecution.py, tcms/rpc/tests/test_testexecution.py
if all executions are completed/not-completed,
on `TestExecution.update` API calls
@atodorov ATM you need to refresh the page in order to see that the status of the test run has been changed. this is not ideal IMO. I think it will be best if after the API call to change the status of the execution we make another one to fetch the latest info about the test run and update the according fields
=> Set TR to finished/not-finished

tcms/rpc/api/testcase.py, tcms/rpc/tests/test_testcase.py, tcms/testcases/static/testcases/js/get.js
Breaking Change: Modifies return information of "TestCase.add_component"
RPC API
Closes #2145
=> Fixes #2145: Fixes removing a component from a TestCase

tcms/testcases/tests/test_views.py
=> Fixes #1615: Adds tests for tcms.testcases.views.EditTestCaseView

kiwi_lint/__init__.py, kiwi_lint/api_distinct.py, kiwi_lint/missing_permissions.py, kiwi_lint/utils.py, tcms/bugs/api.py, tcms/rpc/api/classification.py, tcms/rpc/api/testcase.py, tcms/rpc/api/testexecution.py, tcms/rpc/api/testexecutionstatus.py, tcms/rpc/api/testrun.py
- Bug.filter()
- Classification.filter()
- TestCase.filter()
- TestExecution.filter()
- TestExecutionStatus.filter()
- TestRun.filter()
and also add a pylint checker to catch these issues!
=> API: Add .distinct() to API methods that are missing it

tcms/kiwi_auth/tests/test_forms.py, tcms/kiwi_auth/tests/test_views.py
=> test: Add tests for tcms.kiwi_auth.forms

tcms/static/js/tags.js, tcms/static/style/patternfly_override.css, tcms/templates/include/attachments.html, tcms/templates/include/comments_for_object_template.html, tcms/templates/include/tags_card.html, tcms/testruns/templates/testruns/get.html
Closes #2263 
Closes #2264 
@atodorov this is a draft implementation(but pretty much all needed), what do you think about it? Would be good to generalise it such that it applies to `get` views of other models(Test Plan, Test Case) as well? If so, we will have to add conditions for some corner cases. 
Also, will you be able to share some hints on how to write tests for this?
=> Fixes #2263, #2264: Removes links and icons from print

tcms/settings/common.py, tcms/static/js/utils.js, tcms/telemetry/static/telemetry/js/testing/utils.js, tcms/testruns/forms.py, tcms/testruns/static/testruns/js/mutable.js, tcms/testruns/templates/testruns/mutable.html, tcms/testruns/tests/test_views.py, tcms/testruns/views.py
changes the form so that we can filter by
Product -> TestPlan -> Build
=> Allow TestRun creation without pre-selected TestPlan. Fixes #2281

tcms/templates/include/tc_executions.html
introduced in 22c6ff7
CC @APiligrim
=> Bug-fix: wrong field name in HTML template

tcms/testruns/static/testruns/js/search.js, tcms/testruns/templates/testruns/search.html
@AirinB the previous PR got closed because I've deleted the target branch. I've rebased the source branch towards the latest master and opened this PR instead.
=> Update runs/search with 4 new fields Refs. #1928

tcms/core/middleware.py, tcms/core/views.py, tcms/settings/common.py, tcms/templates/initdb.html, tcms/urls.py, tests/test_docker.sh
=> WEB based database initialization

tcms/testcases/tests/test_models.py
- define input values and expected values as parameters to test
method
- adjust the imports
- work with TestExecutionFactory instead of the TestExecution model
directly
CC @APiligrim
=> Convert the previous test to a parameterized one

tcms/testplans/tests/test_admin.py
=> test: Test ReadOnlyHistoryAdmin

tcms/core/utils/mailto.py, tcms/kiwi_auth/forms.py
=> fix: Emails should translate into server language

docs/source/installing_docker.rst, tcms/kiwi_auth/forms.py, tcms/kiwi_auth/tests/test_views.py
=> Add init-db docs and auto-activate first user

tcms/core/management/commands/initial_setup.py
Refs https://github.com/kiwitcms/enterprise/issues/88
=> Use initial_setup to create public tenant.

tcms/testcases/static/testcases/js/get.js
I am currently working on this file and am tired of reverting my editor formatting it the right way, so I am commiting these changes AND only these change
=> Reformat `tcms/testcases/static/testcases/js/get.js`

tcms/static/js/utils.js
in `updateTestPlanSelectFromProduct`.
Fixes #2467
=> Support single product ID value

tcms/testruns/static/testruns/js/get.js
I am interacting with this file, so pushing this early to prevent big diffs in PRs with changes.
=> Run `eslint --fix` on `testruns/static/testruns/js/get.js`

tcms/bugs/static/bugs/js/get.js
- run `eslint --fix`
- rename manually the snake_case identifier to camelCase
=> Fix eslint issues in `bugs/js/get.js`

tcms/handlers.py, tcms/settings/common.py, tcms/tests/test_handlers.py
WARNINGS:
- Renamed SafeJSONRPCHandler to KiwiTCMSJsonRpcHandler
- New handler KiwiTCMSXmlRpcHandler
- Updated MODERNRPC_HANDLERS setting !
=> API: serialize timedelta to seconds

.github/workflows/testing.yml, docs/source/modules/tcms.core.checks.rst, docs/source/modules/tcms.core.rst, tcms/core/apps.py, tcms/core/checks.py, tcms/core/tests/test_checks.py, tests/test_docker.sh
this will be used in the future
=> installation-id

tests/test_utf8_uploads.py
resolves an issue in Circle CI !
=> tests: Use python3 instead of python in Docker test file

tcms/locale/en/LC_MESSAGES/django.po
see https://github.com/kiwitcms/github-marketplace/pull/65
=> Add new translation strings

tcms/rpc/api/category.py, tcms/rpc/api/classification.py, tcms/rpc/api/forms/management.py, tcms/rpc/api/forms/testcase.py, tcms/rpc/tests/test_category.py, tcms/rpc/tests/test_classification.py
I needed creation of Classification through the XMLRPC API and would eventually need Category creation as well. Implemented both.
Fixes #2705
=> Issue 2705

docs/source/installing_docker.rst, docs/source/modules/tcms.core.management.commands.rst, docs/source/modules/tcms.core.management.commands.upgrade.rst, tcms/core/management/commands/upgrade.py, tests/migrations-rollback
The command will help to perform post-upgrade tasks for Kiwi TCMS installations.
=> Management command to perform post-upgrade tasks

tcms/core/management/commands/initial_setup.py, tcms/core/management/commands/refresh_permissions.py, tcms/utils/permissions.py
In order to support tenant group permissions.
=> Refactor refresh_permissions command and supporting functions

tcms/kiwi_auth/admin.py
Patch originally proposed as an issue comment. Closes #2610
=> Convert two assignment statements to augmented source code.

tcms/bugs/static/bugs/js/search.js, tcms/locale/en/LC_MESSAGES/django.po, tcms/testruns/static/testruns/js/get.js, tcms/testruns/templates/testruns/get.html
=> Add "Assigned to me" filter on Test run page

requirements/base.txt
https://docs.djangoproject.com/en/4.0/releases/4.0.8/
=> Update Django to 4.0.8

.gitignore, tcms/package-lock.json
so that Dependabot may upgrade some of the transient dependencies
=> Commit package-lock.json in git

tcms/bugs/static/bugs/js/mutable.js, tcms/static/js/utils.js
this should have been part of da9dbf26e1539115ed9ef7975297f4eb726b05c2
=> Move shared functions into utils.js

tcms/npm-install, tcms/package-lock.json
removes 150 packages from node_modules/
=> Don't install devDependencies for Node.js packages

tcms/core/tests/test_utils.py, tcms/core/utils/mailto.py
Remove deprecated setDaemon() method
=> Remove deprecated setDaemon() method

tcms/core/tests/test_admin.py, tcms/kiwi_auth/admin.py, tcms/kiwi_auth/tests/test_admin.py
Deletion of the last superuser should fail with a warning.
=> Prohibit deletion of the last superuser

tcms/testruns/static/testruns/js/search.js, tcms/testruns/templates/testruns/search.html
=> Show Start/Stop timestamp columns on Search Test Runs page

tcms/testcases/admin.py
this will make it easier to debug issues
=> Show traceback info during IssueTracker health check

tcms/core/tests/test_collectstatic.py
because of https://github.com/sehmaschine/django-grappelli/issues/1022
=> Add test for collectstatic command

tcms/testplans/static/testplans/js/get.js, tcms/testruns/static/testruns/js/get.js
=> Refactor calls to delete in javascript

tcms/testplans/views.py
You cannot clone Test Plan with different Product, Version select does not work as expected.
1. We have plan with product 1:
3. We change product and version:
5. After `Clone` we got error:
=> [TestPlan] Fix clone with different product

.github/workflows/coverity_scan.yml, .github/workflows/docker.yml, .github/workflows/integration_bugtracker.yml, .github/workflows/lint.yml, .github/workflows/sanity.yml, .github/workflows/security.yml, .github/workflows/testing.yml, Dockerfile, Dockerfile.buildroot, setup.py
b/c minimum required version by Django 5 is Python 3.10!
=> Start testing and building with Python 3.11

.github/workflows/lint.yml, Dockerfile, requirements/devel.txt
=> Send Referer: header for container HEALTHCHECK command

etc/nginx.conf, tcms/core/middleware.py, tcms/settings/common.py, tcms/templates/admin/base_site.html, tcms/templates/base.html, tests/test_http.sh
see https://plausible.io/privacy-focused-web-analytics for more details. Blog post on kiwitcms.org coming soon.
set ``ANONYMOUS_ANALYTICS``  to False to disable.
=> Enable anonymous/GDPR compliant analytics via https://plausible.io/

tcms/bugs/templates/bugs/get.html, tcms/static/style/patternfly_override.css, tcms/testcases/templates/testcases/get.html, tcms/testplans/models.py, tcms/testplans/templates/testplans/get.html, tcms/testruns/templates/testruns/environment.html, tcms/testruns/templates/testruns/get.html
warning: for some reason replacing inline styles for checkbox/ellipsis inside testplans/get.html doesn't work while testruns/get.html !!!
=> Replace more inline styles with CSS class

.github/workflows/integration_bugtracker.yml, .github/workflows/sanity.yml, .github/workflows/testing.yml, docs/source/hardware_performance.rst, docs/source/installing_docker.rst, tests/test_docker.sh, tests/test_http.sh
see announcement at the top of
https://github.com/actions/runner-images/blob/ubuntu22/20240401.4/images/ubuntu/Ubuntu2204-Readme.md
=> Replace `docker-compose` with `docker compose`

docs/source/configuration.rst, docs/source/installing_docker.rst
and provide more links and context for Enterprise installations
=> Update installation instructions for Docker

tcms/core/management/commands/initial_setup.py
Refs https://github.com/kiwitcms/tenants/pull/229
=> Adjust initial_setup calls for the new initialize_tenants command

tcms/core/management/commands/initial_setup.py
if the KIWI_TENANTS_DOMAIN environment variable was found
=> Automatically configure domain during initial_setup

requirements/base.txt, tcms/issuetracker/types.py
before upgrading dependate packages
=> Update PyGithub v1 as an intermediate

tcms/static/style/patternfly_override.css
will be used to replace inline style= attributes
=> Add a few more custom CSS styles

.circleci/config.yml, .github/workflows/docker.yml, Makefile
quay.io/kiwitcms/version -> quay.io/kiwitcms/upstream
=> Update name of private repository on quay.io

tcms/locale/uk_UA/LC_MESSAGES/django.po
from https://github.com/kiwitcms/Kiwi/issues/3833#issuecomment-2459482440
=> Update Ukrainian translation

tcms/testcases/views.py
=> Change redirect on test case clone

tcms/management/admin.py
=> Added search field for tags

tcms/static/js/utils.js, tcms/telemetry/static/telemetry/js/index.js, tcms/testcases/static/testcases/js/search.js, tcms/testruns/static/testruns/js/mutable.js
also move discoverNestedTestPlans() into utils.js to minimize the possibility of circular imports
=> Display nested Test Plan(s) in select drop-down on New Test Run page

tcms/issuetracker/bugzilla_integration.py, tcms/issuetracker/tests/test_bugzilla.py
to fetch more info about reported bugs via Bugzilla integration interface
=> Implement Bugzilla.details() method

requirements/base.txt
https://docs.djangoproject.com/en/5.2/releases/5.1.11/
=> Update Django from 5.1.10 to 5.1.11

tcms/testcases/templates/testcases/mutable.html
=> Add Cancel button for "New TestCase" & "Edit TestCase" pages
