kiwitcms/Kiwi

- tcms/core/utils/__init__.py
- tcms/templates/plan/common/json_plan_runs.txt
- tcms/templates/run/common/json_runs.txt
- tcms/testcases/tests.py
- tcms/testcases/views.py
- tcms/testplans/tests.py
- tcms/testplans/urls/plans_urls.py
- tcms/testplans/views.py
- tcms/testruns/tests/test_views.py
- tcms/testruns/views.py
New DataTableResult is introduced to handle search objects pagination
and sorting for generating response data for rendering in DataTable in
user's web browser.
Search plans, cases, runs and runs in plan page are modified to use this
new class.
Signed-off-by: Chenxiong Qi <qcxhome@gmail.com>
Conflicts:
tcms/testcases/views.py
tcms/testplans/views.py
tcms/testruns/views.py
> Refactor datatable response

- tcms/core/contrib/auth/backends.py
- tcms/core/contrib/auth/forms.py
- tcms/settings/common.py
- tcms/utils/permissions.py
also by default make all users have is_staff permissions so they
can add Products, Builds, Versions, etc. via the ADMIN menu!
If you don't want this to be possible (e.g. products and builds
are synced automatically from a product database) you have to
define another default group and revoke some of its permissions!
> Upon registration assign default group permissions if none set

- Makefile
- docs/source/configuration.rst
- docs/source/guide/admin.rst
- tcms/profiles/models.py
- tcms/profiles/tests.py
- tcms/templates/case/get_details_case_run.html
- tcms/templates/registration/login.html
- tcms/testcases/tests.py
These are all minor changes so I've bundled them together in one PR. See commit log.
> A few bug fixes and improvements for the next release

- tcms/templates/xmlrpc.html
- tcms/xmlrpc/tests/test_views.py
- tcms/xmlrpc/views.py
also removed unused variables in context, updated the template
to make it easier to assert if something has been rendered and
added a sanity test for that
> Update how we render the XMLRPC info page. Fixes #80

- docker-compose.yml
- tcms/testplans/models.py
- tcms/testplans/tests.py
> Fix for #80

- tcms/issuetracker/types.py
- tcms/testruns/tests/test_views.py
@GotfatherThe turns out the underlying jira library tries to connect
automatically when a jira.JIRA object is created. When the
Issue Tracker is not fully configured (i.e. missing base_url,
api_url, api_username, api_password) then the library will default
to localhost and fail to connect to the JIRA server.
This causes the TestRun report view to timeout and fail.
This commit adds tests for all supported issue trackers and also
fixes the JIRA implementation to not connect if not configured.
> If JIRA isn't fully configured then don't connect. Fixes #100

- tcms/report/data.py
- tcms/report/tests.py
The report will simply display 'None' for the tester name which
means this case has not been executed yet (iow its tested_by
attribute has not been set).
> Don't crash reports when there are untested TestCaseRuns. Fix #88

- .travis.yml
- Dockerfile
- docs/source/set_dev_env.rst
- package.json
- tcms/core/tests/test_views.py
- tcms/settings/test/__init__.py
- tcms/templates/patternfly.html
- tcms/tests/storage.py
In later versions Patternfly has changed the location of dependent
libraries and that broke the template. However we're seeing this
because the Dockerfile was not taking into account the package.json
file in the project but rather installing patternfly directly!
@GodfatherThe sorry for the late reply. Can you please checkout if this fixes the problem for you?
> Pin patternfly version to 3.30 and update templates. Fixes #120

- docs/source/configuration.rst
- tcms/core/contrib/auth/tests.py
- tcms/core/contrib/auth/views.py
- tcms/core/utils/mailto.py
- tcms/settings/common.py
`DEFAULT_FROM_EMAIL` is the standard name for this setting and is used by other Django apps/email backends.  There's no point for us keeping a setting with a different name!
> Rename EMAIL_FROM to DEFAULT_FROM_EMAIL. Fixes #128

- tcms/management/tests.py
- tcms/templates/mail/edit_case.txt
- tcms/testcases/helpers/email.py
- tcms/testcases/models.py
- tcms/testcases/tests/test_models.py
- tcms/testplans/models.py
* TestCaseText.get_plain_text is refactored to return an object with
four plain text converted from HTML.
* Remove TestPlainText.get_plain_text as it is not used in code.
Signed-off-by: Chenxiong Qi <qcxhome@gmail.com>
> Refactor get_plain_text

- tcms/core/tests/test_views.py
- tcms/templates/navigation.html
when email contains + sign, e.g. user+qa@example.com this was causing
the search views to not find any Test Plans or Test Runs. The reason
is because the email address needs to be properly urlencoded before
passing it as query string argument to the search views!
Without urlencoding the + sign is then decoded as a space within
the search view!
Originally spotted by @Akulavenkatesh
> [bug-fix] Properly urlencode emails in personal menu

- tcms_api/tests/test_everything.py
root cause: using stale cache to compare to
> Fix failing API client tests

- tcms/core/ajax.py
After the changes introduced in #193 , some code has been left in `ajax.py` which is not used.
> Removed unused code from ajax.py

- tcms/core/contrib/auth/tests.py
- tcms/core/contrib/auth/views.py
- tcms/settings/common.py
setting this to False will force manual user approval by site administrators.
> New setting AUTO_APPROVE_NEW_USERS. Fixes #203

- tcms/core/ajax.py
- tcms/core/tests/test_ajax.py
As discussed in #222 the SQL queries in `ajax.py` needed to be refactored into Django queries.
> Refactor SQL queries in ajax.py to Django queries

- tcms/core/db.py
- tcms/settings/devel.py
- tcms/settings/test/__init__.py
- tcms/settings/test/mysql.py
- tcms/settings/test/postgresql.py
Small fixes in `tcms.settings` and its inner modules plus `tcms.core.db`. 
1. Added flag for `pylint` to ignore the wild-card imports, used by Django
2. Replaced some unused variables with `_`
> Fixed pylint issues in tcms.settings and tcms.core.db

- tcms/core/ajax.py
- tcms/core/tests/test_ajax.py
- tcms/management/models.py
After adding tests for `ajax.info` in #268 we now have the freedom to refactor the method. This includes pulling the inner class `Objects` into outer `_InfoObjects` class (adding separate tests in the process) and refactoring the nested if logic in the`info` method itself
> Refactor ajax.info

- Dockerfile
- docs/source/installing_docker.rst
- docs/source/set_dev_env.rst
- etc/kiwi-httpd.conf
this is also necessary because we make use of the 'secrets'
module in the authentication backend and this module is available
only for Python 3.6!
> Update to Python 3.6. Fixes #91

- tcms_api/xmlrpc.py
Changed constructor in CookieTransport, which created a problem when creating SafeCookieTransport.
> Fix for : 'TypeError: __init__() got an unexpected keyword argument 'use_datetime'.'

- tcms/templates/email/post_run_save/email.txt
Email notifications for test runs have empty Test Plan url and
Product fields. Correct the blocktrans assignments to fix this.
Fixes #353
Signed-off-by: Matt Porter <mporter@konsulko.com>
> Fix test run email notification content

- docs/source/conf.py
- readthedocs.yml
- tcms/core/contrib/auth/models.py
Remove previous workarounds and add a config file.
> Configure ReadTheDocs for Python 3.6

- .travis.yml
- Makefile
- README.rst
- requirements.txt
NOTE: using curly braces to define the pylint stage b/c otherwise
allow_failures doesn't work. This needs to be updated after we fix
all pylint errors!
Actually make the Coverity add-on work by fixing the build command
parameter (hint: these are the cov-build options) and making this
target execute for master branch.
> Convert CI builds to stages

- requirements/base.txt
- tcms/settings/common.py
- tcms/templates/navigation.html
- tcms/urls.py
Makes it possible for power users and admins to generate tabular
reports:
http://django-report-builder.readthedocs.io/en/latest/howto/
You will have to know the existing DB schema if you want to create
your own reports. See:
http://kiwitcms.readthedocs.io/en/latest/db.html
Please comment at:
https://github.com/kiwitcms/Kiwi/issues/452
> Tech preview: Django Report Builder

- docs/source/installing_docker.rst
- tcms/settings/product.py
downstream distributions of Kiwi TCMS (e.g. custom docker images)
only need to provide the settings they wish to override, not
duplicate everything from product.py
Documentation is updated to match.
> product.py now tries to import local_settings.py

- tcms/issuetracker/bugzilla_integration.py
- tcms/issuetracker/github_integration.py
- tcms/issuetracker/jira_integration.py
It seems that three typos went unnoticed in #496 
This has got me thinking. Why don't we commit our pylint log? Or introduce some kind of hook that runs pylint and compares it to the previous version. This way, we may keep track of all the pylint errors in a centralized manner, and will easily see this kind of errors, when opening a PR. Also, currently we have no guarantee that more pylint issues won't be commited. Using some kind of checks will give us that guarantee.
> Fixed typo in pylint disable comments

- tcms/testruns/forms.py
- tcms/xmlrpc/api/testrun.py
- tcms/xmlrpc/tests/test_testrun.py
NOTES:
'product' is no longer required
'product_version' is no longer required
'manager' and 'default_tester' can be usernames or IDs
> Don't use product_version when creating TestRun via API. Fix #522

- tcms/xmlrpc/api/testrun.py
The code that works with status field is broken and it must instead
work with stop_date field. This patch makes it possible to at least
use the API without crashing.
reported in:
https://stackoverflow.com/questions/52865463/xmlrpc-client-fault-when-calling-testrun-update
> Hot-fix for error caused by TestRun.update via API

- tcms/report/data.py
- tcms/report/forms.py
- tcms/report/tests.py
- tcms/report/views.py
- tcms/search/__init__.py
- tcms/static/js/advance_search.js
- tcms/templates/report/common/search_run.html
- tcms/templates/report/testing-report/by_plan_build_with_rates.html
- tcms/templates/report/testing-report/by_plan_tag_with_rates.html
- tcms/templates/report/testing-report/per_build_report.html
- tcms/templates/report/testing-report/per_plan_build.html
- tcms/templates/report/testing-report/per_plan_tag.html
- tcms/templates/report/testing-report/per_priority_report.html
This removes the obsolete `fmt_queries` method. What it did, is replace some of the keys of the `queries` object. These keys are later exposed on the front-end, so after this change, we will be exposing the keys as they are. This may be a bit ugly at the beginning, but this problem may be solved by refactoring the templates in general.
> Removed fmt_queries. Fixes #330

- tcms/testcases/views.py
Browsing through old issues I have created I found this one. Then, when looking for the method calls I saw that we are no longer passing the optional `pk_enough` param. IMO this is the most that can be done for this method as of now.
> Remove unused parameter from plan_from_request_or_none. Refs #303

- tcms/report/views.py
- tcms/testplans/tests/test_views.py
- tcms/testruns/tests/test_data.py
- tcms/testruns/tests/test_models.py
- tcms/testruns/tests/test_report_view.py
- tcms/testruns/tests/test_update_caserun_status_view.py
- tcms/testruns/tests/test_views.py
The `too-many-ancestors` warning was displayed many times for different test classes - there we have a lot inheritance. The maximum `pylint` allows is 8. We can override it with a `.pylintrc` file, but since all of them were in tests, I suggest we disable it inline. This way it would still be valid for the business logic, where it may come handy.
Another minor fix - disabled `no-member` warning for `test_run.cc.count` - `test_run` is created through calling `TestRunFactory()`. `TestRunFactory` has a method `cc` and `TestRun` has a member `cc` (which has `.count()`). However, `pylint` thinks `test_run` is a `TestRunFactory` instance and `test_run.cc` is a reference to the method, which has no `.count()`. Clearly, `pylint` is wrong and that is why we silence it.
> Minor pylint fixes for tests

- tcms/core/templatetags/extra_filters.py
the list of all extensions is at:
https://python-markdown.github.io/extensions/#officially-supported-extensions
> Enable nl2br Markdown extension. Fixes #623

- tcms/testruns/forms.py
- tcms/xmlrpc/api/testrun.py
- tcms/xmlrpc/tests/test_testrun.py
This PR fixes #554 . Also,I have added an test for successful update. @atodorov do tell if you think I need to add more test cases. 
On a side note, I am thinking of opening an issue about renaming all of the classes and methods that cointain `XMLRPC`, to something more generic, because now we have JSON-RPC API as well, and the same methods are used by it, so their names are a bit misleading. Do you think this kind of change in necessary?
> Fix TestRun.update API not processing stop_date

- Dockerfile
- httpd-foreground
The docker container can not be restarted because the httpd pid file is left over, when stopping the container. This adds a start script which simply removes the left over files.
This is taken from the official httpd dockerfile on dockerhub.
> make docker container restartable

- tcms/static/js/tcms_actions.js
- tcms/static/js/testplan_actions.js
The purpose of this PR is to clear the left-overs from #636 
After examining the JS files, used by the existing template I found out that these two ids - `add_id_product` and `add_id_product_version` have `onclick` handlers, but are not present in any other files. Therefore, the existing handlers are never used anymore. Also, the custom `popupAddAnotherWindow` was used only by these handlers, so I had to remove that too. The `js-cancel-button` is used in `plan/clone.html`, so we cannot yet remove it.
> Remove left-over js from deletion of plan/new.html

- tcms/static/js/utils.js
A temporary workaround until this template is refactored
into Patternfly, when bootstrap-switch can be used,
and the following js code will work
> Surround selectpicker call with try-catch. Fixes #695

- docs/source/modules/tcms.xmlrpc.api.forms.rst
- docs/source/modules/tcms.xmlrpc.api.forms.testplan.rst
- tcms/testplans/forms.py
- tcms/testplans/views.py
- tcms/xmlrpc/api/forms/testplan.py
- tcms/xmlrpc/api/testplan.py
- tcms/xmlrpc/forms.py
As discussed in #677 
> delete NewPlanForm.tag and EditPlanForm.author since they are not used
DONE
> delete classes that are not used, but are only inherited once - XMLRPCNewPlanForm,XMLRPCEditPlanForm
copy the fields from these intermediate classes inside the ones found under xmlrpc/forms.py
remove the intermediate classes
DONE - The forms were removed and their field were put into their respective anchestors
>under xmlrpc/ better organize the forms into smaller groups, e.g. xmrpc/api/forms/testplan.py or similar and update the imports in the API modules.
DONE
> investigate all of the above form classes for unused fields
this is part of the change above (separate commits for everything) and you should be careful for:
Some of these fields are not properly covered by tests and my approach …
> Form fields removal and form merges

- tcms/xmlrpc/api/testcase.py
- tcms/xmlrpc/tests/test_testcase.py
- will now fail if trying to add components linked to another
Product. This will prevent typing the component name in the UI
(without autocomplete) and hitting enter from adding the
component
- now returns serialized TestCase object
> [api] TestCase.add_component() changes

- tcms/locale/de_DE/LC_MESSAGES/django.po
- tcms/locale/en/LC_MESSAGES/django.po
- tcms/locale/fr_FR/LC_MESSAGES/django.po
- tcms/locale/sl_SI/LC_MESSAGES/django.po
- tcms/locale/zh_CN/LC_MESSAGES/django.po
- tcms/locale/zh_TW/LC_MESSAGES/django.po
- tcms/testcases/static/testcases/js/mutable.js
- tcms/testcases/templates/testcases/mutable.html
- tcms/testcases/views.py
things left to be done:
* currently, the `is_automated` switch is not working. I am going to spend time on this once #727
`configure_product_on_load ` has been copied to `utils.js` since it is already defined in two place - `testcase_actions.js` and `testplan_actions.js`. Since those files are going to be deleted at some moment, I suppose that the right place for this util function is `utils.js`. I suppose we can live with this duplication for now
`testcases/js/mutable.js` introduces some more duplication - 
```javascript
$('#add_id_product').click(function () {
return showRelatedObjectPopup(this);
});
document.getElementById('id_product').onchange = function () {
$('#id_product').selectpicker('refresh');
update_category_select_from_product();
};
$('.selectpicker').selectpicker(); …
```
> Convert New TestCase page to Patternfly 

- package.json
https://snyk.io/vuln/SNYK-JS-MARKED-73637
> [security], [medium] Explicitly require marked v0.6.1 to fix ReDoS

- tcms/testplans/models.py
- tcms/testplans/tests/tests.py
I was a bit annoyed with new cases showing up at the top of my cases list instead of the bottom. This change will ensure a test cases will get a `sortkey` of the highest `sortkey` in the plan + 10. You can still create a case with a custom `sortkey`. The first case in the plan will get `0` as a `sortkey`.
> TestPlan.add_case() sets the sortkey to highest in plan + 10

- tcms/testcases/views.py
I found that in the views.py file, where function A was called, no appropriate parameters were passed in.
> Fixes #674

- tcms/issuetracker/types.py
This adds a dummy implementation of an issue tracker. 
`is_adding_testcase_to_issue_disabled` returns `True` because adding a test case to issues is unavailable. This means that trying to do this through the UI will result in an error being shown in the screen. An alternative would be to put it to `True` and then it will try to call `add_testcase_to_issue`, which is empty, so nothing will happen and success will be returned
> Add Dummy issue tracker. Fixes #289

- tcms/testcases/migrations/0006_merge_text_field_into_testcase_model.py
- tcms/testcases/migrations/0009_populate_missing_text_history.py
in version 6.5 the TestCase model was updated to store the text
into a single field called `text` instead of 4 separate fields.
During that migration historical records were updated to have
the new `text` field but values were not properly assigned.
The "effect" of this is that in TestCaseRun records you were not
able to see the actual text b/c it was None.
This commit ammends 0006_merge_text_field_into_testcase_model for
installations which have not yet migrated to 6.5 or later. We also
provide the data-only migration 0009_populate_missing_text_history
which will inspect the current state of the DB and copy the text
to historical records.
> [db] populate missing TestCase.text history

- tcms/testcases/migrations/0006_merge_text_field_into_testcase_model.py
- tcms/testcases/migrations/0009_populate_missing_text_history.py
using test_case.history.latest() doesn't work b/c we don't have
the historical manager available during migrations so we need to
query the object directly.
The test suite doesn't catch this b/c initially there is no data
and the for loop isn't executed.
> [db] Use query to update HistoricalTestCase in migrations

- .travis.yml
because kiwitcms-tenants needs PostgreSQL we enable testing with it for all PRs alongside MariaDB.
> Enable testing with PostgreSQL 10 on PRs

- tcms/package.json
There is a bug from version 3.3.5 onwards, which displays ON switches as OFF ones.
This change can be reverted once https://github.com/Bttstrp/bootstrap-switch/issues/683 is closed
> Use bootstrap-switch version 3.3.4 Fixes #916

- Dockerfile
because that may lead to errors from other packages which sometimes
are not easy to see (e.g. if pip falls back to an older version).
Right now we have:
ERROR: markdown 3.1 has requirement setuptools>=36, but you'll
have setuptools 28.8.0 which is incompatible.
which despite being reported as error doesn't seem to break anything.
> Upgrade pip and setuptools inside Docker image

- tcms/core/models/base.py
- tcms/kiwi_auth/forms.py
- tcms/kiwi_auth/tests.py
because it uses an internal cache and causes email notifications
from tenants/public to use the wrong URL.
> Don't use Site.objects.get_current()

- docs/source/modules/tcms.telemetry.api.rst
- docs/source/modules/tcms.telemetry.rst
- docs/source/modules/tcms.telemetry.views.rst
- tcms/settings/common.py
- tcms/telemetry/api.py
- tcms/telemetry/static/telemetry/js/testing/breakdown.js
- tcms/telemetry/templates/telemetry/testing/breakdown.html
- tcms/telemetry/urls.py
- tcms/telemetry/views.py
- tcms/urls.py
Initial touches on Test Case Breakdown View.
This PR contains working Test Case Breakdown page showing some data. 
The purpose of this PR is to lay the foundations of the page. There are few questions:
1. Is this the preferred approach? - all the data is fetched via the API and the charts are drawn on the client-side, with the view returning an almost empty template that serves as a placeholder
2. Is the validation in the RPC method done right?
3. Are those the right tools to draw the charts? Patternfly wrapper of D3.js, and also some pure D3.js
The visualisation is a bit ugly now, and the colors are not right, but that can be changed easily if the other things are done right. 
Please review the draft PR and comment on what the MVP of the page is, so that I know what to focus on in the …
> Add Telemetry TestCase Breakdown view

- tcms/kiwi_auth/forms.py
- tcms/kiwi_auth/urls.py
- tcms/kiwi_auth/views.py
the internal cache in .get_current() doesn't produce correct results when working with kiwitcms-tenants.
> Override PasswordResetForm because of Site.objects.get_current()

- kiwi_lint/__init__.py
- kiwi_lint/empty.py
> Add EmptyClassChecker

- tcms/testcases/tests/test_models.py
Cherry-pick only the tests from #878 since the rest has already been introduced into master.
> Add test for email_case_deletion(). Refs #878

- tcms/settings/common.py
- tcms/telemetry/api.py
- tcms/telemetry/static/telemetry/css/testing/status-matrix.css
- tcms/telemetry/static/telemetry/js/testing/status-matrix.js
- tcms/telemetry/static/telemetry/js/testing/utils.js
- tcms/telemetry/templates/telemetry/testing/status-matrix.html
- tcms/telemetry/urls.py
- tcms/telemetry/views.py
- tcms/testruns/models.py
This is the outline for Testing/StatusMatrix.
What is left:
-latest comment in case of failure.
-Links to bugs will be shown in each cell with a summarized bug table below the charts.
Few takeaways:
- we have some duplicated logic in `utils.js` - `update_build_select_from_product`, `update_category_select_from_product`, `update_component_select_from_product` and the new `updateTestCaseSelectFromProduct` have a lot of similarities and a base method can be extracted to avoid code duplication. I can do that now or open an issue for later? Also, the method names should be change to camelCase as this is preffered in js.
- the way we serialize domain objects is not optimal. we use `Model.toxmlrpc(query)` which fetches the objects from the db, based on `query` and serializes them. However, in …
> Add TestingStatusMatrixView

- tcms/settings/common.py
> overwrite timezone configuration with env

- tcms/testruns/views.py
because the underlying form resturns None or a User object and
there is no point in querying the DB again with the same value.
CC @RMadjev
> [refactoring] Use default_tester instead assignee_tester variable

- tcms/kiwi_auth/views.py
- tcms/telemetry/views.py
- tcms/testcases/views.py
- tcms/testplans/views.py
- tcms/testruns/views.py
Disable pylint message for unnecessary checks. Refs #171
> Disable pylint checks for several views, because those views are only selecting/reading data but not modifying it. Refs #171.

- docs/source/admin.rst
- tcms/core/migrations/0001_squashed.py
- tcms/utils/permissions.py
NOTE: administrators of existing applications will need to
apply these permissions by hand via the Admin section of the
application.
> [db] Apply linkreference permissions to Tester group. Fixes #881

- .dockerignore
- Dockerfile
- Dockerfile.buildroot
- Makefile
- tests/check-build
- build Kiwi TCMS PyPI tarballs inside buildroot
- build Python dependencies inside buildroot
- compile translations inside buildroot
- copy /venv/ to the outside and then inside runtime image
- reduces overall image size from 1.01 GB to 699 MB
- simulates a multi-stage build but doesn't depend on it explicitly
because there are version requirements which we don't want to force
onto people, see:
https://docs.docker.com/develop/develop-images/multistage-build/
- works in our own build infrastructure which is RHEL based and
docker (especially the binaries coming from Docker, Inc.) are not
first class citizens
cc @clee
> Use buildroot/runtime docker images

- tcms/telemetry/api.py
- tcms/testruns/models.py
This aims to define the API that is going to be used for the Test Case Health Telemetry feature.
From the blog post is seems that this will be all the information we are going to need in order to draw the corresponding tables.
Sample response:
```json
[
{
"case_id": 1,
"case_summary": "Test login with non-existing username",
"count": {
"fail": 1,
"pass": 11
}
},
{
"case_id": 2,
"case_summary": "Test login with existing username and wrong password",
"count": {
"fail": 0,
"pass": 12
}
},
{
"case_id": 3,
"case_summary": "Test login with existing username and right password",
"count": {
"fail": 1,
"pass": 11
}
}
]
```
> Test Case Health Telemetry API

- docs/source/modules/tcms.xmlrpc.api.rst
- docs/source/modules/tcms.xmlrpc.api.utils.rst
- requirements/base.txt
- tcms/issuetracker/types.py
- tcms/settings/common.py
- tcms/settings/devel.py
- tcms/templates/case/get_details_case_run.html
- tcms/testcases/static/testcases/js/get.js
- tcms/testcases/templates/testcases/get.html
- tcms/xmlrpc/api/bug.py
- tcms/xmlrpc/api/testexecution.py
- tcms/xmlrpc/api/utils.py
there are still things which need to be done, especially around documenting how to override the existing behavior and caching backends. 
Also the feature is partially implemented b/c TR page needs refactoring to Patternfly before we can continue further. Will land together with the test of the bugtracker changes next month.
> Fetch additional bug details and display them in TestCase page

- tcms/testruns/urls.py
- tcms/testruns/views.py
For
￼     executions = executions.distinct()
The query use group by case_run_id, so I think the distinct is irrelevant.
> Refactor testruns get view to class-based

- tcms/issuetracker/types.py
in this way we create object to connect to the remote end only
once, which should improve speed of work when working often with
bugs directly from Kiwi TCMS. This also makes it possible to
still have multiple IT integrations in the same instance b/c they
will have unique base URLs.
> Cache Issue Tracker connections per base_url. Fixes #290

- tcms/core/widgets.py
FontAwesome is loaded automatically by Patternfly and this
auto-download causes some sort of override/conflict/version mismatch
and some of the icons disappear.
> Don't auto-download FontAwesome for SimpleMDE. Fixes #905

- Dockerfile.buildroot
- tests/check-build
this will ensure that we always ship the latest possible
translations in binary form, ready for use by gettext.
Note: in version 7.0 we may have shipped stale .mo files b/c
some strings for Bulgarian have definitely been translated but
they didn't appear even after rebuilding the image.
> [bug-fix] Remove and compile .po files in check-build

- CHANGELOG.rst
Fixed link for "'Delete' menu item in Bugs page Fixes 1153" as it pointed to issue 1154
> Update changelog for v7.1

- tcms/tests/__init__.py
to skip this class appropriately. Otherwise we get
Run 0 tests and not see the errors when they exist
this makes the errors in #1190 visible.
> Override PermissionTestCase.__call__(), not run()

- tcms/telemetry/api.py
The current logic always misses the first status of a test run.
This fixes that
> Fix counting big in execution trends

- tcms/templates/case/get_details.html
RPC methods which add comments only need 1 permission so should
HTML templates. Adding comments (reviewing a TC) is independent
action and in theory you could have a very limited User/Group
which is allowed to do only this.
> Check for permissions in HTML template. Closes #961

- tcms/telemetry/static/telemetry/js/testing/execution-trends.js
- tcms/telemetry/static/telemetry/js/testing/status-matrix.js
Change the query from case to run means one less join on the back-end
and also shows all data in the corner case, where the cases are deleted.
> Fix telemetry queries 

- tcms/static/js/testcase_actions.js
- tcms/static/js/testplan_actions.js
- definition of serializeCaseForm2() in testcases_actions.js is
functionally identical
should have gone into 7b575403e5c91a8e979beb64b8d1fb1744ec39b0
but I merged #1244 without realizing I didn't commit all files.
Rookie mistake :-(
> JavaScript: Remove duplicate serialzeCaseForm()

- tcms/static/js/testrun_actions.js
- tcms/static/style/base.css
- tcms/templates/run/get.html
- tcms/templates/run/get_case_runs.html
- tcms/templates/run/table_executions.html
- tcms/testruns/tests/test_views.py
- tcms/testruns/views.py
> In TR page; TE row and TE details -> status & comment widget: still using older icons. This is controlled via .btn_<status_name> styles in base.css. 
I still don't feel like deleting this CSS. Will do it as the last of this task.
> In TR page; bulk edit menu; Status menu -> no icons along status names! In base.css this was controlled via styles named .<status_name>Blue9 which are no longer used. 
It is using the `icon` and `color` property now. And it is sorted by `weight`
> Leverage new Test case status icons

- tcms/templates/run/get_case_runs.html
Also, remove pading on elements, which made the dropdowns inconsistent with the other ones.
There was a 15 px padding on all the elements in the list.
I could have removed remove it if I remove the class `btnBlueCaserun` of the dropdown, but that breaks the whole layout AND functionality, because there are jQuery selectors that depend on this class.
So I decided to just inline the css that will ovveride this padding. Not the cleanest solution in terms of code, but the least painful one + having in mind that this page will be refactored to Patternfly soon, it's not worth it spending more time and effort on it.
> Fix broken drop-down when status names are too long

- tcms/settings/test/__init__.py
will cause test_discovery.py to be automatically executed and
makes pylint happier
> Add missing __init__.py & adjust an import outside toplevel

- tcms/testcases/migrations/0010_remove_bug.py
https://stackoverflow.com/questions/59321756/migration-from-v6-4-to-v7-2-fails-with-column-execution-id-cannot-be-null
> db: skip bugs which are attached directly to TCs

- tcms/rpc/api/forms/testcase.py
- tcms/rpc/api/testcase.py
- tcms/rpc/tests/test_testcase.py
- ModelForm allows edditing all model fields except many-to-many
- will allow removal of BaseCaseForm, Refs #708, #812
> [api] Use ModelForm for TestCase.update(). Fixes #630

- requirements/base.txt
- requirements/tarballs.txt
- tcms/rpc/api/testcase.py
- ignore 'product' parameter which is still sent by older clients
> API: add backwards compatibility for TestCase.create()

- tcms/tests/storage.py
This PR makes `tcms.tests.storage.RaiseWhenFileNotFound` capable of finding static files in a Windows environment, where the backslash is used as the file path separator.
Solves this question on StackOverflow: [Static file “debug_toolbar/css/print.css” does not exist when starting Kiwi Tcms](https://stackoverflow.com/questions/55297178/static-file-debug-toolbar-css-print-css-does-not-exist-when-starting-kiwi-tcms)
> Normalize file path separator in storage class

- tcms/static/style/base.css
This PR adds a `1em` left padding to ordered lists in the detail display of test cases, in order to ensure that list markers have enough space to sit inside their respective lists without flowing out through the left border.
`1em` is just enough to properly contain markers of <= 2 digits.
Containing markers of larger sizes will mean bumping this value upwards. But I think `1em` is perfect for the average use case &mdash; 99 seems to me a sensible limit to the number of items in a list made for humans 😇 😇 😇.
__IMAGE__: Before Change
__IIMAGE__: After Change
> Add left padding to ordered lists in test cases. Fix #339

- .github/workflows/lint.yml
- .travis.yml
Add `.github/workflows/lint.yml`, which lists the GitHub actions, which we
will use for linting. (We may have more linting actions in the same
file, for example pylint, or more actions is separate files)
Inside the file, define `flake8` job, which does the bare minimum
to run flake8 on our codebase:
- checkout the code
- install python
- install flake8
- run flake8
This takes ~23 seconds, compared to the ~3 minutes it takes Travis CI to
run the flake8 task. The difference is that Travis does much more
prerequisites, like installing additional dependencies, which we
don't need in this case.
In order to verify this is working and indeed linking I made this: https://github.com/asankov/Kiwi/pull/2
A branch on top of this one, which intentionally introduces a flake8 error, and we can see that …
> Add GitHub action for running flake8

- tcms/testplans/static/testplans/js/search.js
Set Search Test Plan result table page length to 100 rows.
> Set Test Plans search result table rows to 100 per page

- tcms/static/js/testrun_actions.js
- tcms/templates/run/status_statistics.html
on TestExecutionStatus
from https://stackoverflow.com/questions/1291942/what-does-javascriptvoid0-mean/1293130#1293130:
```
<a href="#"> is a common alternative which might arguably be less bad. However you must remember to return false from your onclick event handler to prevent the link being followed and scrolling up to the top of the page.
```
> Prevent link follow-up when filtering

- tcms/bugs/apps.py
- tcms/bugs/tests/test_models.py
- tcms/settings/common.py
- tcms/signals.py
- tcms/templates/email/post_bug_save/email.txt
- tcms/tests/factories.py
This PR adds email notification about assigned bugs on bug creation.
If assignee is not None, they are notified of the created bug to which they've been assigned.
The body of the email notification contains a summary of the bug and a link to the bug's detail page.
------
**PREVIOUSLY:**
~This PR adds email notification about assigned bugs on add/edit actions.~
~* __ADD__: On bug creation, if assignee is not None, they are notified of the created bug which they've been assigned to.~
~* __EDIT__: On subsequent bug saves, if assignee is not None, and is different from the previous assignee in the database, then the recently assigned assignee is notified of the assignment.~
~The body of the email notification contains a summary of the bug and a link to the bug's detail page.~
> Notify assignee of bug assignment. Fix #1154

- tcms/bugs/static/bugs/js/search.js
- tcms/templates/navbar.html
- tcms/testcases/static/testcases/js/search.js
- tcms/testplans/static/testplans/js/search.js
- tcms/testruns/static/testruns/js/search.js
The number of rows on page should be configurable. DEFAULT_PAGE_SIZE is now used to set this for Test Plan search results.
> Make use of DEFAULT_PAGE_SIZE setting for Test Plans search table rows

- tcms/utils/settings.py
- tcms/utils/tests/test_local_settings_dir.py
because Django's LazySettings() modifies the underlying
object during application loading and that breaks for us.
Figure out the scope from the caller's context
(inspired by django-split-settings)
The current approach is used by Transifex:
https://code.djangoproject.com/wiki/SplitSettings#UsingalistofconffilesTransifex
> Another take on how we read settings overrides

- tcms/core/middleware.py
- tcms/settings/common.py
this is a legacy leftover which doesn't make any sense
> Remove CsrfDisableMiddleware. Closes #297

- tcms/issuetracker/base.py
- tcms/issuetracker/types.py
The Components queryset is converted to space delimited string for proper display in bug reports.
Closes #1157
> Fix display of Components in automatic bug reports

- tcms/rpc/api/auth.py
this method is not needed for tcms-api b/c kerberos logins are
handled via PSA kerberos plugin and the API client needs to
respect that. See https://github.com/kiwitcms/tcms-api/issues/22
> [api] Remove Auth.login_krbv() method

- .travis.yml
- .travis/my.cnf
- docker-compose.yml
- docs/source/configuration.rst
- tcms/settings/common.py
also add short section in documentation to point out to more documentation
> MariaDB: change charset and collation to utf8mb4. Closes #327

- tcms/telemetry/static/telemetry/js/testing/execution-trends.js
Delete trailing whitespaces in `execution-trends.js`
> Hide empty values in Execution trends chart tooltip

- tcms/bugs/tests/test_permissions.py
- tcms/rpc/api/forms/testrun.py
- tcms/rpc/tests/test_testrun.py
because this is the default format in which datetime values are
serialized via PRC. We should acccept the same format at the very
minimum.
Note: this is used by methods in the upcoming RobotFramework plugin.
I am keeping the existing format for backwards compatibility.
> api: TestRun.update() will now accept %Y-%m-%d %H:%M:%S format

- tcms/settings/common.py
this is a setting which is relevant only for
kiwitcms-tenants/django-tenants and for Kiwi TCMS represents a
subset of all applications accessible to each tenant. These are
the appilications which hold private data for that tenant.
In the past we've had issues where adding a new app into
INSTALLED_APPS (e.g. tcms.bugs) didn't make it into TENANT_APPS
and resulted in all users being able to share bugs which we didn't
want.
Because TENANT_APPS is always a subset of INSTALLED_APPS it is not
possible to check if we've added something to INSTALLED_APPS but
forgot to add it into TENANT_APPS. That's why I'm moving this
setting here and using it as a temporary variable to construct the
full list of INSTALLED_APPS.
> Define TENANT_APPS b/c impossible to check for errors otherwise

- tcms/telemetry/static/telemetry/css/testing/status-matrix.css
- tcms/telemetry/static/telemetry/js/testing/status-matrix.js
- make the table header clickable, with link to the run
- add a tooltip that shows the summary of the test run
- wrap the text of the first column
> Status matrix page: show only ID of test run

- tcms/testruns/static/testruns/js/get.js
- tcms/testruns/templates/testruns/get.html
- tcms/testruns/views.py
Takes #1436 rebases it to the latest upstream and adjusts HTML & JavaScript.
> Test run patternfly status bar - Obsoletes #1436

- docs/source/configuration.rst
- tcms/core/tests/test_sendtestemail.py
- tcms/settings/common.py
I've tried to improve the documentation and the main config file to make e-mail setup more user friendly. Since users can spare some digging in Django documentation I hope that we will have less e-mail related support questions.
> Clarify e-mail settings and testing. Closes #1070

- .github/workflows/lint.yml
- .travis.yml
> Add Doc8  linter to GitHub workflow. Closes #1551

- tcms/static/js/utils.js
- tcms/templates/navbar.html
- tcms/testruns/static/testruns/js/get.js
- tcms/testruns/templates/testruns/get.html
Encapsulate the html showing the server's timezone into
a `span` with id and data attribute.
When clicking the OFF button, read the value from there
and use `moment-with-timezone` to converr the date which is
in the client's timezone to the server's timezone.
For the purpose we need to vendor the `moment-timezone-with-data.js`,
because it contains all the data about timezones, time differences, etc.
Without doing that, all convertions fall back to UTC and I found no other way
to download the file (via npm or something else).
> Send the stop_date in server timezone.

- tcms/testruns/static/testruns/js/get.js
- tcms/testruns/templates/testruns/get.html
- wrap the stop date in `span.stop-date` for easy manipulation.
- upon completing the API call, set the html of that DOM field to:
- `-` if plan is set to running
- the actual stop date if plan is set to finished
> Update stop date dinamically on Test Run completion

- .github/workflows/sanity.yml
- .travis.yml
- Added check-docs-source-in-git to sanity.xml
- Removed Added check-docs-source-in-git from travis
> Add check-docs-source-in-git to sanity.xml

- .travis.yml
- docs/source/admin.rst
- tcms/bugs/tests/factory.py
- tcms/bugs/tests/test_models.py
- tcms/bugs/tests/test_permissions.py
- tcms/bugs/tests/test_views.py
- tcms/core/tests/test_admin.py
- tcms/issuetracker/types.py
- tcms/rpc/api/testexecution.py
- tcms/settings/common.py
- tcms/tests/factories.py
- tcms/urls.py
- all tests should be passign with and without this App
- specific tcms.bugs related tests should be skipped when the
App is not found in INSTALLED_APPS
> Start testing with the internal bug tracker disabled. Refs #1370

- .coveragerc
Omitted the utils/tests from coverage reports.
Not sure if this is the right way.
> Omit utils/test from coveralls. Fix #1631

- Dockerfile
- tests/runner.sh
- tests/test_mysql_psql.sh
because we tend to install only the libraries for the DB drivers.
Last time when we switched to MariaDB 10.3 we broke this!
These binaries are the main DB cli tool which is also used by
`manage.py dbshell`, which in turn is referenced in some use-cases
around truncating and restoring data into existing databases!
> Add tests for presense of mysql/psql binaries in container

- tcms/testruns/static/testruns/js/get.js
- tcms/testruns/templates/testruns/get.html
contains the changes from #1546 
currently, UI looks like this:
> Render test case text and notes for each TestExecution in TestRun page

- kiwi_lint/__init__.py
- kiwi_lint/forms.py
Resolves #1384. Add a lint checker class to check if all forms inherit from ModelForm.
>  Add a lint checker class to check for ModelForm inheritance

- tcms/static/js/bugs.js
- tcms/templates/include/bugs_table.html
- tcms/testcases/static/testcases/js/get.js
- tcms/testcases/templates/testcases/get.html
this template will be plugged into every test execution row in the test run page
> Extract bugs table into reusable template

- tcms/static/js/jsonrpc.js
if for some reason an RPC call doesn't return a result but ends
in an error (an exception on the server side) then alert the user
about what happened.  This makes problems more visible instead of
silently hiding them.
> Alert on JSON-RPC error. Closes #625, #1333

- Makefile
- tcms/bugs/api.py
- tcms/issuetracker/base.py
- tcms/rpc/api/attachment.py
- tcms/rpc/api/auth.py
- tcms/rpc/api/bug.py
- tcms/rpc/api/build.py
- tcms/rpc/api/component.py
- tcms/rpc/api/testcase.py
- tcms/rpc/api/testexecution.py
- tcms/rpc/api/testplan.py
- tcms/rpc/api/testrun.py
- tcms/rpc/api/user.py
- tcms/rpc/api/version.py
- tcms/rpc/serializer.py
- tcms/rpc/utils.py
- tcms/testcases/views.py
- tcms/testplans/models.py
- tcms/testplans/views.py
Resolves #1192. Enable pylint plugin pylint.extensions.docparams and resolve errors
Can I get some clarification on a few things I'm not clear on to complete the doc-params : 
- I'm not quite sure what `op_type` is in:
https://github.com/kiwitcms/Kiwi/blob/dd295479eae3b73bb1b99811c610f5d20657f5ca/tcms/rpc/utils.py#L90
and why its used here and why the TypeError is raised.
- I'm not familiar with how to document kwargs in docparams. May I please get a sample to go off on, for example in:
https://github.com/kiwitcms/Kiwi/blob/dd295479eae3b73bb1b99811c610f5d20657f5ca/tcms/rpc/api/auth.py#L14
>  Enable pylint plugin pylint.extensions.docparams and resolve errors

- tcms/core/middleware.py
mark_safe() here receives hard-coded/well-known values, not
untrusted input
> Disable check from bandit

- docs/source/admin.rst
- tcms/issuetracker/tests/test_bugzilla.py
- tcms/issuetracker/tests/test_github.py
- tcms/issuetracker/tests/test_gitlab_ee.py
- tcms/issuetracker/tests/test_jira.py
- tcms/issuetracker/tests/test_kiwitcms.py
- tcms/issuetracker/tests/test_redmine.py
- tcms/issuetracker/types.py
- tcms/rpc/api/bug.py
- tcms/rpc/api/utils.py
- tcms/rpc/tests/utils.py
- tcms/settings/common.py
- tcms/testcases/admin.py
- tcms/testcases/migrations/0014_update_issutracker_types.py
- All of them are now listed as dotted class paths under the
EXTERNAL_BUG_TRACKERS setting
- DB migration will rename existing records
- tcms.issuetracker.types.from_name() is replaced with
django.utils.module_loading.import_string() which returns the
class at the end of a dotted path
- update documentation
Refs #1151 - will make overriding bug-tracker integration easier
Refs https://github.com/kiwitcms/github-app/issues/25 - will open
the path to providing a custom GitHub Issues integration for the
GitHub App
> Rework how external bug tracker integrations are discovered

- tcms/bugs/api.py
- tcms/bugs/tests/test_api.py
This PR adds tests for the `add_tag()` api method in `tcms/bugs/api.py` as per #1597
> Add tests for API method tcms.bugs.api.add_tag(). Refs #1597

- tcms/bugs/api.py
- tcms/bugs/tests/test_api.py
This PR adds tests for the `remove_tag()` api method in `tcms/bugs/api.py` as per #1597
> Add tests for API method tcms.bugs.api.remove_tag(). Refs #1597

- tcms/bugs/tests/test_api.py
This PR adds tests for the `filter()` api method in `tcms/bugs/api.py` as per #1597
> Add tests for API method tcms.bugs.api.filter()

- tcms/settings/common.py
we need both of them to be changed at the same time for emailing
to work properly.
> Slightly adjust how email settings are described

- tcms/bugs/tests/test_views.py
This PR adds (non-permissions related) tests for the view `New` in tcms/bugs/views.py as per #1598
* Permissions related tests already exists in tcms/bugs/tests/test_permissions.py
> Add tests for tcms.bugs.views.New -- Refs #1598

- docs/source/guide/testcase.rst
Updated documentation to reflect that Test Cases cannot 
be rearranged from within a Test Run but only from Test Plan.
Fixes #1805
> [doc] Update regarding TC re-order function

- Makefile
Resolves #1774. Add new linter to warn about missing backwards migrations callable in RunPython
> Add new linter to warn about missing backwards migrations callable

- requirements/base.txt
- requirements/tarballs.txt
- tcms/core/templatetags/extra_filters.py
bleach-whitelist 0.0.11 has been deprecated and the package has
been renamed
> Replace bleach-whitelist with bleach-allowlist. Closes #1813

- Makefile
- tcms/bugs/migrations/0002_add_permissions.py
- tcms/core/migrations/0001_squashed.py
- tcms/management/migrations/0003_squashed.py
- tcms/testcases/migrations/0001_initial.py
- tcms/testcases/migrations/0006_merge_text_field_into_testcase_model.py
- tcms/testcases/migrations/0007_convert_is_automated_to_boolean.py
- tcms/testcases/migrations/0009_populate_missing_text_history.py
- tcms/testcases/migrations/0010_remove_bug.py
- tcms/testcases/migrations/0014_update_issutracker_types.py
- tcms/testplans/migrations/0005_squashed.py
- tcms/testruns/migrations/0004_squashed.py
- tcms/testruns/migrations/0006_rename_test_case_run_to_test_execution.py
- tcms/testruns/migrations/0007_test_execution_statuses.py
Refs #1774 Fix linter errors in migrations except for recently created missing-backwards-migration-callable. Added `--module-naming-style=any` to silence invalid-name errors in migration module names.
> Fix linter errors in migrations

- tcms/testruns/static/testruns/js/get.js
- tcms/testruns/templates/testruns/get.html
contains the changes from #1546 
just the HTML for the bulk action button.
the buttons look like this:
my idea is that whenever the user clicks them a modal would pop up, in which the user would provide the necessary input - https://www.patternfly.org/v3/pattern-library/widgets/#modal
> Testrun executions bulk actions skaffold

- tcms/core/history.py
in some cases, e.g. custom data restore, we're saving objects with
all of their fields set, including the PK/ID field. Without this
patch instance.pk will be present in .pre_save() but the actual
record doesn't exist in the DB yet hence an exception will be raised.
With this change instance.previous will be None in case the object
doesn't exist in the DB and the code in .post_save() will take care
to execute the diff_objects() function only when instance.previous
isn't None.
> Handle history when importing objects with ID field set

- tcms/static/js/simplemde_security_override.js
- fix typo in the highlight function name from the previous commit
- keep re-parsing the textarea as the user types and keep loading
new grammars b/c they may be writing a completely new text which
didn't reference a particular language before.
> Parse text as user types and auto-load syntax highlight

- tcms/rpc/api/testcase.py
- tcms/testcases/static/testcases/js/get.js
internally it is used in only 1 place while Component.filter is much
more common and better covered with tests.
To filter components for a particular TC use:
JSON-RPC call -> ('Component.filter', [{'cases': TC.id}], callback);
> api: Remove TestCase.get_components() in favor of Component.filter()

- tcms/bugs/tests/test_permissions.py
- tcms/bugs/tests/test_views.py
This PR adds tests for the view `Edit` in `tcms/bugs/views.py` as per #1599
> Add tests for tcms.bugs.views.Edit -- Closes #1599

- tcms/testruns/static/testruns/js/get.js
- tcms/testruns/templates/testruns/get.html
- tcms/testruns/views.py
on top of #1842 because a lot of stuff are reused
tested with local Kiwi TCMS tracker
> Testrun executions one click bug report

- kiwi_lint/__init__.py
- kiwi_lint/db_column.py
Resolves #736. Add a lint checker class to check for use of db_column argument in model field definition.
@atodorov I had tried `node_is_subclass` with Django's `django.db.models.Field` but I'm not sure which node/node_attribute to check in this case. May I please get clarification on I could use to check? So far, I have just gone with checking attribute node; checking if the `node.attrname` ends with 'Field' or 'Key' and checking the node's expression name is 'models' to tell apart from form fields
> Add DbColumnChecker lint checker class

- tcms/bugs/api.py
- tcms/rpc/api/__init__.py
- tcms/rpc/api/attachment.py
- tcms/rpc/api/auth.py
- tcms/rpc/api/bug.py
- tcms/rpc/api/build.py
- tcms/rpc/api/category.py
- tcms/rpc/api/classification.py
- tcms/rpc/api/component.py
- tcms/rpc/api/plantype.py
- tcms/rpc/api/priority.py
- tcms/rpc/api/product.py
- tcms/rpc/api/tag.py
- tcms/rpc/api/testcase.py
- tcms/rpc/api/testcasestatus.py
- tcms/rpc/api/testexecution.py
- tcms/rpc/api/testexecutionstatus.py
- tcms/rpc/api/testplan.py
- tcms/rpc/api/testrun.py
- tcms/rpc/api/user.py
- tcms/rpc/api/version.py
- tcms/telemetry/api.py
because we expose two types of RCP APIs - XML and JSON
and using only XML-RPC is misleading
just a quick find and replace I felt like doing
> Docs: replace references to `XML-RPC` with `RPC`

- tcms/core/management/commands/migrations_order.py
- tcms/signals.py
> Add 2 new params when calling 'migrate' from 'migrations_order'

- docs/source/conf.py
- docs/source/configuration.rst
- docs/source/modules/tcms.kiwi_auth.backends.rst
- docs/source/modules/tcms.kiwi_auth.rst
- requirements/tarballs.txt
- tcms/kiwi_auth/backends.py
- tcms/settings/common.py
- tcms/tests/__init__.py
now that every view requires permissions we don't need
GlobalLoginRequiredMiddleware anymore!
> Remove django-glrm

- tcms/settings/devel.py
This PR makes the location of the default database platform agnostic.
On Windows, the default database will now resolve to an appropriately named file in the directory used for temporary files.
> Fix name of default database in settings

- tcms/issuetracker/kiwitcms.py
- tcms/issuetracker/tests/test_kiwitcms.py
- tcms/rpc/tests/test_bug.py
also, tests for Kiwi TCMS tracker and `Bug.details` API method
> Don't fail if Kiwi TCMS tracker can't find bug

- tcms/static/js/bugs.js
- tcms/testcases/static/testcases/js/get.js
- tcms/testruns/static/testruns/js/get.js
- tcms/testruns/templates/testruns/get.html
Also, move `fetchBugDetails` and `assignPopoverData`
to tcms/static/js/bugs.js so that it can be reused
> Add bug popover to TestRun executions table

- tcms/templates/menu_items.html
as an attempt to make this menu a bit more visible. Will look like this:
> Replace ... with 3 cogs icon for object level menu in navbar

- tcms/bugs/tests/test_permissions.py
- tcms/bugs/tests/test_views.py
This PR adds tests for the view `AddComment` in `tcms/bugs/views.py` as per #1600
> Add tests for tcms.bugs.views.AddComment -- Closes #1600

- requirements/base.txt
- tcms/kiwi_auth/forms.py
- tcms/templates/registration/registration_form.html
- tests/check-build
If you want to enable this then add the following to your settings:
```
if 'captcha' not in INSTALLED_APPS:
INSTALLED_APPS.append('captcha')
RECAPTCHA_PUBLIC_KEY = '......'
RECAPTCHA_PRIVATE_KEY = '.....'
RECAPTCHA_USE_SSL = True
```
For more info see https://www.google.com/recaptcha/admin/
> Make it possible to use reCAPTCHA during registration

- tcms/bugs/tests/test_permissions.py
- tcms/bugs/tests/test_views.py
This PR adds tests for the view `Search` in `tcms/bugs/views.py` as per #1601
> Add tests for tcms.bugs.views.Search -- Closes #1601

- tcms/static/js/utils.js
This functions is used in both the `refactor_testrun_ui` and
`refactor_testplan_ui` branches, so better share it this way
cc: @RMadjev
> Add `animate` function to `utils.js`

- tcms/testruns/static/testruns/js/get.js
- tcms/testruns/templates/testruns/get.html
~~For whatever reason ATM the `animate` callback is executed twice and the bug counter and list is updated with 2 bugs(not 1). I will try to troubleshoot this and solve it before merging this.~~
02d07575b483d7ca4d02d7510326a00d2e0e41a2 solved it - there were 2 elements with this class, so the `fadeOut` was executed twice.
> Refresh execution row after reporting a bug

- tcms/testruns/static/testruns/js/get.js
- tcms/testruns/templates/testruns/get.html
Not sure if styling and positioning is ideal. I am welcome to suggestions.
> Render test execution information

- tcms/testplans/static/testplans/js/get.js
- tcms/testplans/templates/testplans/get.html
for clues we take the height of the info card next to the document
text and expand/collapse trying to match that height for visual
consistency.
> Collapse TestPlan document card if text is very long

- tcms/rpc/api/testcase.py
- tcms/rpc/tests/test_testcase.py
Returns information about TestCase position inside TestPlan.
For example `TestCase.sortkeys({'plan': 3})`
> New API: TestCase.sortkeys(). Fixes #444

- tcms/package.json
- tcms/rpc/api/testplan.py
- tcms/testplans/static/testplans/js/get.js
- tcms/testplans/templates/testplans/get.html
NOTES:
- uses Sortable.js for drag & reorder
- manual sorting button is located after A-Z button in toolbar
- NEW API method TestPlan.update_case_order()
- Manual reorder & API require the testcases.change_testcaseplan
permission
- toolbarDropdowns() is called from within toolbarEvents() b/c
it really doesn't make sense to have this as stand-alone function
- toolbarEvents() is moved within the TestCases.filter() callback
b/c we need the list of test cases to be fully initialized so we
can get the initial sorting order and use it later
WARNINGS:
- may want to unbind the on-click event for rows if users are
having problems with the rows expanding while dragging them
- the page doesn't use sortkey for initially displaying the rows
of test cases because this field isn't available in the API …
> Implement drag & reorder functionality & new API

- .github/workflows/lint.yml
- Makefile
- kiwi_lint/__init__.py
- kiwi_lint/generic_foreign_key.py
Resolves #1303 Add a lint checker to warn against defining GenericForeignKey fields in models
> Add a lint checker to warn against defining GenericForeignKey fields in models

- tcms/rpc/api/forms/testrun.py
- tcms/rpc/api/testexecution.py
- tcms/rpc/tests/test_testexecution.py
When changing status the close_date field will be updated according to status.weight
cherry-picked from the refactoring branch.
> API TestExecution.update() will adjust close_date. Fixes #1820

- docs/source/admin.rst
- docs/source/installing_docker.rst
- docs/source/modules/tcms.core.management.commands.refresh_permissions.rst
- docs/source/modules/tcms.core.management.commands.rst
- tcms/core/management/commands/refresh_permissions.py
- tcms/utils/permissions.py
> Management command to refresh permission objects.

- tcms/rpc/tests/test_testexecutionstatus.py
This is a draft PR for adding automated tests for missing coverage in `tcms.rpc.api.testexecutionstatus` module according to #1626. This is my first time working with such a large codebase and I understand there might be a lot of problems with the PR so I'm looking for someone to help me figure out how I can improve and correct the code with a review.
> [WIP] add test for testexecutionstatus #1626

- tcms/rpc/tests/test_testcasestatus.py
Addresses #1624 
Add automated Tests for tcms.rpc.api.testcasestatus. Two test cases with two different test case status have been made for querying.
- `test_filter_case_status` filters case status using name.
- `test_filter_case_status` filters case status using case id.
> Add automated tests for tcms.rpc.api.testcasestatus

- tcms/rpc/tests/test_priority.py
Addresses #1622 
- `TestPriorityFilter` tests Priority.filter method
- `TestPriorityFilterPermissions` tests permissions for Priority.filter method
> Add Automated tests for missing coverage in tcms.rpc.api.priority

- tcms/rpc/tests/test_testexecution.py
I've added the test cases for handling the functionality of `TestExecution.remove_comment` as that was the only function remaining out of the code coverage. I was having trouble figuring out when and if I have to setup a separate test to check permissions, and needed some clarity regarding it.
> add test for TestExecution #1625

- tcms/rpc/tests/test_classification.py
Addresses #1621 
- `TestClassificationFilter` tests Classification.filter method
- `TestClassificationFilterPermissions` tests permissions for Classification.filter method
> Add automated test for rpc.api.classification

- tcms/rpc/api/auth.py
- tcms/rpc/tests/test_auth.py
Addresses #1620 
- `TestAuthLogin` tests Auth.login method
- `TestAuthLogout` tests  Auth.logout method
According to docstring [here](https://github.com/kiwitcms/Kiwi/blob/ac31b26f129aef0bb4b0768334cdad4eeb092086/tcms/rpc/api/auth.py#L20), Auth.login method work with either username or email, but actually, it fails with email as a parameter.
> Add automated tests for missing coverage in tcms.rpc.api.auth

- tcms/issuetracker/azure_boards.py
- tcms/issuetracker/bitbucket.py
Fixed the below problems in RTD;
- AzureBoards
1. Example url line was misalinged. 
2. Unnecesary bullet removed for base_url.
- BitBucket 
1.   There is no `info` tag in RTD. So it is changed as `note` for api_password.
2.   Unnecessary bullet removed for base_url.
> Documentation fixes for BitBucket and AzureBoards IssueTrackers.

- tcms/testcases/tests/test_views.py
fixes #1614 
- TestNewCase.test_form_invalid tests validity of the forms in NewCaseView on /cases/new view.
> Add Automated tests for missing coverage in tcms.testcases.views.NewCaseView

- tcms/testplans/static/testplans/js/get.js
- when udpating internal state preserve the current sortkey
- when redrawing a row remove it from the list of exanded rows
b/c it may have changed. This also fixes a problem with comments
editor b/c when the row is redrawn the editor widget is gone
> Be more robust when keeping internal state for TP page

- tcms/bugs/admin.py
- tcms/testcases/admin.py
- tcms/testplans/admin.py
- tcms/testruns/admin.py
also makes it harder for anyone (even if they have permissions) to
just remove everything from the database as we've seen recently
happening on public.tenant.
> Remove delete_selected action from admin, see 4d79de41

- .github/workflows/integration_bugtracker.yml
and update pip as an attempt to fix issues:
requests 2.25.0 requires chardet<4,>=3.0.2, but you'll have
chardet 4.0.0 which is incompatible.
pygithub 1.54 requires requests<2.25,>=2.14.0, but you'll have
requests 2.25.0 which is incompatible.
which can't be reproduced locally with 3.6/latest pip
> Fix testing bugtracker integration

- tcms/core/tests/test_middleware.py
Closes #1605 
------
Initially, I chose to use actual GET/POST requests and test the working of the middlewares, but I changed my mind after looking into [Django's source code](https://github.com/django/django/blob/master/tests/middleware/tests.py).  I tried to follow how they have written tests for their middlewares.
> Fixes #1605 - Adds tests for tcms.core.middleware

- tcms/management/tests/test_admin.py
@atodorov I have added tests for missing coverage. Do you want tests to be added for other things too? 
I referenced existing tests in `test_admin.py` of other apps and they don't test anything other than things that are added by Kiwi's code. 
Closes #1610
> Fixes #1610: Adds tests for tcms.management.admin

- tcms/rpc/api/forms/testrun.py
- tcms/rpc/api/testrun.py
- tcms/rpc/tests/test_testrun.py
Cherry-pick 1 commit adding more tests because the rest of the missing tests expose a bug that needs to be fixed.
> Cherry-pick tests from PR 2256

- tests/runner.sh
Should catch things like:
/usr/share/beakerlib/beakerlib.sh: line 431: /usr/share/beakerlib/ya.sh: No such file or directory
grep: /var/tmp/beakerlib-*/TestResults: No such file or directory
> tests: Catch & fix beakerlib failures

- tcms/rpc/tests/test_testrun.py
- tcms/testruns/forms.py
@atodorov could you please check my changes and comment on them? Also in the file tcms/rpc/api/forms/testrun.py should the fields for planned_stop and planned_start be added?
> Update: tests with new assetions to check TestRun.planned_stop. Refs #1928

- docs/source/admin.rst
`delete_stale_comments` is part of django-contrib-comments > 2.0.0 which hasn't been released yet!
> Document useful management commands

- tcms/static/js/utils.js
- tcms/testcases/static/testcases/js/search.js
- tcms/testplans/templates/testplans/get.html
- tcms/testruns/templates/testruns/get.html
because they are deprecated in Chrome browser and lead to
problems for users. Fixes #2100
> Replace beforeunload & unload window events with a function call.

- tcms/testplans/admin.py
- tcms/testplans/tests/test_admin.py
which will open the correct page for creating new test plans
instead of disallowing users to create new objects!
> Point TestPlanAdmin add button to correct URL

- tcms/rpc/tests/test_testexecution.py
- tcms/testcases/tests/test_models.py
- tcms/testruns/models.py
Hello @atodorov, could you please give a recommendation or any advice on how to write test cases for the new start_date and renamed stop_date changes? Also should I add the new property of TestExecution.expected_duration or not yet?
Also for the current commit I made, I was referencing this task from the issue:
`API method TestExecution.update() or the UpdateExecutionForm() - upon changing the status field must set stop_date to the current timestamp if status.weight != 0 (API fix for #1820)`
> Update: API method for start_date and stop_date Refs. #1924

- docs/source/installing_docker.rst
don't tell users to only download docker-compose.yml because it
references other files and Ubuntu doesn't report errors when
those files are missing. See
https://www.youtube.com/watch?v=S7h4OG7aeFA
> Update documentation around docker-compose.yml

- .github/workflows/lint.yml
- Makefile
- kiwi_lint/__init__.py
- kiwi_lint/similar_string.py
- requirements/devel.txt
Fixes #1126 
- Added new linter- `similar-string` to detect similar strings which are marked for translation i.e strings passed to _() or gettext_lazy()
- Used Levenshtein distance from textdistance module which produced quite decent results. You might check if we need more complex similar strings to be detected, I'll use other algorithms for text distance.
> Added similar-string custom pylint linter

- docs/source/modules/tcms.rpc.api.forms.rst
- docs/source/modules/tcms.rpc.api.forms.testexecution.rst
- tcms/rpc/api/forms/testexecution.py
- tcms/rpc/api/testexecution.py
- tcms/rpc/tests/test_testexecution.py
Same as #2144 but opening from a branch to get the bugtracker integration tests executed.
> Refactor add execution link form to use modelform

- tcms/static/style/patternfly_override.css
- tcms/templates/admin/base_site.html
applies white color to error message text so that it is more visible on
the red background.
> Fix CSS class override for admin forms. Fixes #2404

- tcms/static/style/patternfly_override.css
this change will cause large images to fit into the available space on
the screen, e.g. inside test case description cards.
> Apply size constraints for uploaded images. Fixes #2220

- .github/workflows/lint.yml
- tcms/package.json
this config excludes the `no-undef` rule.
Currently, a lot of the errors we get are violating this rule.
This will be fixed when we integrate Webpack in our workflow.
Until then, there is no point in showing these messages, because
they only clutter the output and prevent us from seeing the actual
warnings and errors.
> Add Eslint config

- tcms/kiwi_auth/urls.py
- tcms/kiwi_auth/views.py
- tcms/settings/common.py
if the request is made from a tenant then redirect to the Tenant
authorized users page b/c tenant accounts can't manage users & groups
anyway.
> Redirect ADMIN -> Users and groups according to tenancy

- tcms/testruns/static/testruns/js/get.js
- tcms/testruns/templates/testruns/get.html
Inside the TestRun page users can filter & select the test cases they
want, e.g. ones which are currently failing, and using the toolbar menu
create a new TestRun, for example to track re-testing results,
presumably against a different build!
> New feature: Ability to create TR from selected TCs inside TR

- tcms/testruns/static/testruns/js/get.js
- tcms/testruns/templates/testruns/get.html
API methods TestExecutionStatus.filter() and TestCaseStatus.filter()
will now return translated values depending on the Accept-Language
header sent as part of the API request!
Related: https://github.com/ecometrica/django-vinaigrette/issues/47
> Return translations for API methods. Closes #1966

- tcms/testruns/templates/testruns/mutable.html
- tcms/testruns/views.py
when the page was loaded it didn't properly display the current product
which lead to errors when selecting it.
> Properly initialize Product value on TestRun Edit page. Closes #2514

- tcms/testruns/static/testruns/js/get.js
- 9:7   error  Identifier 'autocomplete_cache' is not in camel case   camelcase
- 306:47  error  Arrow function should not return assignment            no-return-assign
- 716:13  error  'testExecutionRow' is assigned a value but never used  no-unused-vars
This file is now clear of eslint issues.
> Fix eslint issues in `testruns/js/get.js`

- kiwi_lint/views.py
- tcms/telemetry/api.py
Cherry-pick only the API part from #2277. Left the UI changes untouched.
> Add Testing.individual_test_case_health() API method

- tcms/testcases/models.py
Fixes a bug where duretion fields weren't cloned b/c they were not
specified.
> Clone all TestCase fields

- requirements/base.txt
- tcms/rpc/api/testrun.py
- tcms/rpc/tests/test_testrun.py
- tcms/testruns/models.py
- tcms/testruns/templates/testruns/get.html
- tcms/testruns/tests/test_models.py
Iterate over the properties matrix and add separate executions into
the newly created TestRun. Repeat for all test cases which have
properties.
The code support both full and pairwise matrices!
Pairwise is not enabled yet because it needs some UI work.
> Creating a TR will generate TE matrix for TC with properties. Fix #1843

- requirements/base.txt
broken dependencies prevent us from migrating to 4.0
> Update Django to 3.2.10

- tcms/bugs/tests/test_models.py
- tcms/signals.py
- tcms/templates/email/post_bug_save/email.txt
This definitely requires a review :)
- ~~Added the "mailto" call to Bugs/Views.py, not sure if that is the right place.~~
- ~~Changed the email template as "email_create.txt" to distinguish the update and create notification templates.~~
- ~~Not sure how tests will behave in GH Actions.~~
Accepted behaviour: 
- Mails are sent two times, one during `bug.save()` and one during `add_comment()` where both triggers the `post_save `signals for a Bug.
> Fixes #2232 - E-mail notification for comment updates.

- tcms/testcases/models.py
- tcms/testplans/models.py
- tcms/testplans/tests/tests.py
filter query is used to return None on first call if no test case is found.
Close: #2218
> Fix test cases order when cloning TP

- tcms/bugs/static/bugs/js/mutable.js
- tcms/static/style/patternfly_override.css
- tcms/testcases/static/testcases/js/mutable.js
- tcms/testplans/static/testplans/js/mutable.js
The fix checks if there is a parent object and updates the "+" href according to it. 
- Not sure if the fixed places are correct and sufficient. It checks the existence of parent object in "New Bug", "New Test Case" and "New Test Plan" pages. 
- Not sure if it is also required to check on Admin/Management. If that is the case, please help me about the hiearchy of the objects.
> Fix of #2561. Disable + when there is no parent element.

- tcms/locale/en/LC_MESSAGES/django.po
- tcms/testruns/forms.py
- tcms/testruns/models.py
- tcms/testruns/static/testruns/js/mutable.js
- tcms/testruns/templates/testruns/mutable.html
- tcms/testruns/views.py
- Selection is between Full or Pairwise combinations
- Feature is enabled for test runs which contain test cases. This
feature is not shown when creating an empty test run
- This feature isn't supported when subsequently adding new test cases
to test run
The UI mockup proposed in #1931 is much harder to implement currently so
we'll leave it out of scope for now.
> Add matrix selector when creating or cloning Test Run. Closes #1931

- docs/source/configuration.rst
- requirements/base.txt
- tcms/kiwi_auth/forms.py
- tcms/kiwi_auth/templates/captcha_field.html
- tcms/kiwi_auth/tests/test_forms.py
- tcms/kiwi_auth/tests/test_views.py
- tcms/settings/common.py
- tcms/templates/registration/registration_form.html
- tcms/urls.py
- tests/check-build
- self-contained implementation
- does not depend on Google services
- will unblock migration to Django 4
- enabled by default
Settings RECAPTCHA_PUBLIC_KEY, RECAPTCHA_PRIVATE_KEY, RECAPTCHA_USE_SSL
are no longer in use!
New setting: USE_CAPTCHA
"captcha" added to INSTALLED_APPS
New database migration.
> Replace django-recaptcha with django-simple-captcha

- .circleci/config.yml
- .github/workflows/changelog.yml
only when the target branch is of the form `prepare/vX.Y`
And make sure we fail CHANGELOG modifications if the branch name doesn't
match the pattern
> Run docker tests on aarch64 in Circle CI

- tcms/issuetracker/azure_boards.py
- tcms/settings/common.py
- new setting AZURE_BOARDS_API_VERSION, defaults to 6.0
- also allows to be overriden via environment variable AZURE_BOARDS_API_VERSION
> Allow overriding of Azure Boards API version. Closes #2717

- tcms/bugs/templates/bugs/get.html
https://sentry.io/organizations/kiwitcms/issues/3086416250/.
Instead display a textual representation of the user name as it has been
saved in the database at the time the comment was made.
> Don't crash if a comment user has been removed. Fixes KIWI-TCMS-HZ

- tcms/rpc/api/testrun.py
if `default_tester` field is not specified.
> Use request.user in TestRun.create() API method

- tcms/issuetracker/azure_boards.py
- tcms/issuetracker/base.py
- tcms/issuetracker/bitbucket.py
- tcms/issuetracker/bugzilla_integration.py
- tcms/issuetracker/kiwitcms.py
- tcms/issuetracker/tests/test_azureboards.py
- tcms/issuetracker/tests/test_bitbucket.py
- tcms/issuetracker/tests/test_bugzilla.py
- tcms/issuetracker/tests/test_github.py
- tcms/issuetracker/tests/test_gitlab_com.py
- tcms/issuetracker/tests/test_gitlab_ee.py
- tcms/issuetracker/tests/test_jira.py
- tcms/issuetracker/tests/test_kiwitcms.py
- tcms/issuetracker/tests/test_redmine.py
- tcms/issuetracker/types.py
this is a quick solution for the situations where an integration account
is used and all bugs get assigned to it.
> Add Kiwi TCMS reporter to 1-click bug reports. Closes #2591

- tcms/issuetracker/azure_boards.py
- tcms/issuetracker/base.py
- tcms/issuetracker/bitbucket.py
- tcms/issuetracker/bugzilla_integration.py
- tcms/issuetracker/kiwitcms.py
- tcms/issuetracker/tests/redmine_post_processing.py
- tcms/issuetracker/tests/test_redmine.py
- tcms/issuetracker/types.py
- tcms/settings/common.py
- tests/redmine/initialize-data.py
- tests/redmine/seeds.rb
- Rename to _report_issue() which returns tuple of (object, str)
- In case new issue was not created automatically and the method falls
back to manual creation the return value will be (None, str)
- report_issue_from_testexecution() will call _report_issue()
internally and handle the change in return type
NOTES:
- This change is backwards compatible!
- For customized issue tracker integration you will have to apply
the same changes to your custmized code if you wish new functionality,
like post-processing of new issues to work.
> Updates around IssueTrackerType.report_issue_from_testexecution()

- tcms/bugs/tests/test_models.py
- tcms/bugs/tests/test_views.py
- tcms/core/helpers/comments.py
- tcms/signals.py
the root cause here is that the post-save signal is called multiple
times from various triggers. The trigger which we're interested in is
when post-save signal is triggered by the add_comment() function b/c
that's where the important information about bugs is stored.
> Don't send duplicate emails when editting bugs. Fixes #2782

- tcms/static/js/utils.js
Checking the `length` of a null object throws "Uncaught TypeError" in Chrome and "Jquery.Deferred" exception in Firefox. 
I have not observed any functional problems but IMO it would be better to be improved. 
Chrome:
> Jquery deferred: There is no length property of null object.

- requirements/base.txt
This reverts commit 7a5c4a6c579802ee888eda246b3ed6388fdac8fe.
because it causes failures for kiwitcms-tenants when testing:
Debugging in here https://github.com/kiwitcms/tenants/pull/181
Upstream issue -> https://github.com/django-tenants/django-tenants/issues/802
> Revert "Bump django from 4.0.7 to 4.1"

- tcms/issuetracker/types.py
https://github.com/pycontribs/jira/blame/main/jira/client.py#L2591
Project key is passed to `issue_type_by_name` since it raises key error `"Issue type 'Bug' appears more than once."` when there are more than one project.
> Fix for #2929

- .github/dependabot.yml
this is a public registry but Dependabot insists on us specifying username & password fields which we don't have and don't need.
Also with the switch to RHEL 9 UBI we're once again using the latest version of the base image.
> Don't specify custom redhat-catalog container registry

- .github/workflows/integration_bugtracker.yml
- .github/workflows/testing.yml
should get rid of constant failures of their action when using GITHUB_TOKEN
There was an error running the uploader:
Error uploading to https://codecov.io:
Error: There was an error fetching the storage URL during POST:
404 - {'detail': ErrorDetail(
string='Unable to locate build via Github Actions API.
Please upload with the Codecov repository upload token to resolve issue.',
code='not_found')}
> ci: Send results to Codecov.io only if we have a token defined

- .github/workflows/sanity.yml
vs Ubuntu 20.04.5 LTS in older jobs
> ci: No python3-pydot-ng in Ubuntu 22.04.01

- tcms/kiwi_auth/tests/__init__.py
- tcms/kiwi_auth/tests/test_admin.py
- tcms/kiwi_auth/tests/test_forms.py
- tcms/kiwi_auth/tests/test_views.py
- tcms/settings/common.py
- password can’t be too similar to your other personal information.
- password must contain at least 10 characters.
- password can’t be a commonly used password.
- password can’t be entirely numeric.
Existing users are advised to reset their passwords!
> Enable password validators to avoid users chosing weak passwords

- tcms/testruns/views.py
before Product and Version fields are initialized when loading the page directly
> Don't show all builds on Search Test Runs page

- tcms/kiwi_auth/tests/test_admin.py
IIRC the accented characters in some French translations render as HTML utf-8 codes which breaks the assertions. Last time this happened was in f74c3c16b352ada088cb0b34133e7703391c3a3c
> Fix a test failing b/c of French locale

- tcms/rpc/api/attachment.py
- tcms/rpc/api/auth.py
- tcms/rpc/api/bug.py
- tcms/rpc/api/build.py
- tcms/rpc/api/component.py
- tcms/rpc/api/environment.py
- tcms/rpc/api/kiwitcms.py
- tcms/rpc/api/markdown.py
- tcms/rpc/api/plantype.py
- tcms/rpc/api/product.py
- tcms/rpc/api/testcase.py
- tcms/rpc/api/testexecution.py
- tcms/rpc/api/testplan.py
- tcms/rpc/api/testrun.py
- tcms/rpc/api/user.py
- tcms/rpc/api/version.py
b/c it is only used to determine which methods are exposed in the documentation. Currently there are methods which have doc-strings but were not exposed on ReadTheDocs.
> Remove the __all__ attribute in RPC modules

- tcms/testruns/static/testruns/js/get.js
Loading testrun page takes too long for a large number of test executions with parameters.
This is taking so long because of the jQuery append function, which is called every iteration when adding parameters to test execution.
With each iteration, its execution takes more and more time, as the DOM tree grows.
For example, on test run with 2128 test executions, append from beginning takes 4ms, last append takes 154ms:
The fix for this is to use an `.html()` function instead of `.append()`.
Without fix full load takes ~94 seconds:
With fix full load takes ~17 seconds, with each test execution parameters set around 7-10ms (this is the time of the command to get the execution row ```const row = $(`.test-execution-${teId}`)```, there is hardly anything that can be improved here):
~5.5 times …
> [Testruns] Improve loading time on pages with large number of executions

- tcms/kiwi_auth/views.py
- tcms/locale/en/LC_MESSAGES/django.po
which indicates whether the user is viewing records from the main tenant or from an individual tenant. When clicking the menu ADMIN -> Users and ADMIN -> Groups menu as super-user you will always be redirected to the main tenant and since pages look the same that may be very confusing.
> Add INFO message for User/Group pages in Admin panel

- tcms/locale/en/LC_MESSAGES/django.po
- tcms/testcases/admin.py
b/c the fallback to OpenGraph makes it harder to spot misconfiguration errors.
> Improved bugtracker health check messages

- Dockerfile
- add trailing / to avoid redirects
- use IP address instead of hostname
- depending on ALLOWED_HOSTS this request may be blocked
> Small update to HEALTHCHECK command

- tcms/testplans/static/testplans/js/search.js
Recursively find all expanded children of parentRow and hide them.
> [TestPlans] Hide all expanded children, fixes #3245

- tcms/core/templates/dashboard.html
- tcms/templates/navbar.html
- tcms/testcases/templates/testcases/search.html
- tcms/testplans/templates/testplans/search.html
- tcms/testruns/templates/testruns/search.html
There are 2 fixes in this PR:
1. Fix for tag. You can see the problem with this URL: https://public.tenant.kiwitcms.org/runs/search/?tag=some_tag
In form we see:
2. Fix for `My Test Plans` query param. `author__username__startswith` is not correct form variable, `author` is correct. You can check it with 2 URLs:
* **Wrong**: https://public.tenant.kiwitcms.org/plan/search/?author__username__startswith=somebody
* **Correct**: https://public.tenant.kiwitcms.org/plan/search/?author=somebody
> Templates fixes

- tcms/static/js/tags.js
- tcms/testcases/static/testcases/js/get.js
It was noticed when trying to delete test plans.
If you delete several at a time, then there is a multiplication of requests for deletion.
See video with defect:
https://i.imgur.com/hSGW8ed.mp4
> [DataTable] Detach click to prevent request multiplication

- tcms/issuetracker/azure_boards.py
- tcms/issuetracker/base.py
- tcms/issuetracker/bitbucket.py
- tcms/issuetracker/bugzilla_integration.py
- tcms/issuetracker/types.py
to make it easier to override credentials for Issue Tracker integrations
> Define IssueTracker.rpc_credentials property

- tcms/testcases/static/testcases/js/search.js
Filter by Test Run does not work on Search Test Cases view.
The issue is that `#id_run` is simple text field, but query uses `__in` and expects array.
Second way is simply change `params.executions__run__in` to `params.executions__run`.
Improvement can be made with `params.executions__run__in = $('#id_run').val().split(',')`, so you would be able to search by several test runs separated with comma (like Tag field)
> [TestCase] Fix for `#id_run` field query

- tcms/testruns/static/testruns/js/get.js
There are cases when test run is filtered with query param (`?status_id=`).
And because there are no checks for that, if you change statuses, stop date will also change even if TEs from other statuses aren't done yet.
And, btw, changed `delete expandedExecutionIds` to `expandedExecutionIds.splice` because SonarLint wasn't happy:
https://rules.sonarsource.com/typescript/RSPEC-2870/
> [TestRun] Fix filter check, fix `delete expandedExecutionIds`

- tcms/issuetracker/base.py
in order to prevent integrations which define personal ApiTokens to accidentally use a cached version for the same URL but different credentials
> Use tuple as the cache-key for IssueTrackerType.rpc_cache internally

- requirements/base.txt
- tcms/bugs/tests/test_api.py
- tcms/handlers.py
- tcms/rpc/tests/test_attachment.py
- tcms/rpc/tests/test_auth.py
- tcms/rpc/tests/test_build.py
- tcms/rpc/tests/test_category.py
- tcms/rpc/tests/test_classification.py
- tcms/rpc/tests/test_component.py
- tcms/rpc/tests/test_environment.py
- tcms/rpc/tests/test_plantype.py
- tcms/rpc/tests/test_priority.py
- tcms/rpc/tests/test_product.py
- tcms/rpc/tests/test_testcase.py
- tcms/rpc/tests/test_testcasestatus.py
- tcms/rpc/tests/test_testexecution.py
- tcms/rpc/tests/test_testexecutionstatus.py
- tcms/rpc/tests/test_testplan.py
- tcms/rpc/tests/test_testrun.py
- tcms/rpc/tests/test_version.py
- tcms/tests/test_handlers.py
- tcms/urls.py
The goal is to test the current alpha with Kiwi and confirm the future 1.0.0 release won't introduce any regression
> Update django-modern-rpc to 1.0.0a2

- tcms/static/js/utils.js
- tcms/testruns/static/testruns/js/get.js
There are case when rendering after bulk add comment is wrong.
1. Expand test execution:
2. Add comment from toolbar (bulk comment):
3. Previous comments and attachments duplicated:
> [TestRun] Fix row reload on `add_comment`

- tcms/testruns/static/testruns/js/get.js
There are some problems with tags when you change multiple executions of one case.
1. We have parametrized case with tag:
3. Change status of any 3 executions -- tags multiply:
5. Change status of any 2 executions -- tags disappear:
> [TestRun] Fix tags when use `reloadRowFor` on multiple executions

- tcms/core/templates/robots.txt
- tcms/urls.py
b/c everything is login-protected anyway!
Inspired by https://adamj.eu/tech/2020/02/10/robots-txt/ and https://neil-clarke.com/block-the-bots-that-feed-ai-models-by-scraping-your-website/
> Add robots.txt to tell various robots to stop indexing Kiwi TCMS

- Dockerfile
- docs/source/modules/tcms.cron.anonymous_analytics.rst
- docs/source/modules/tcms.cron.rst
- docs/source/modules/tcms.rst
- etc/cron.jobs/anonymous_analytics.sh
- etc/uwsgi.conf
- tcms/cron/anonymous_analytics.py
- triggers every 5 days
- respects settings.ANONYMOUS_ANALYTICS setting
> Add cron job for anonymous analytics

- .github/workflows/testing.yml
- Makefile
- tests/runner.sh
- because newer versions of Firefox and Chrome can't deal with that
- and because we shouldn't have to anyway
- move beakerlib setup inside GHA because this is where it belongs
> Do not execute Docker image tests as root

- requirements/base.txt
Django 5 seems to include some sort of inline JavaScript which is blocked by our Content-Security-Policy and causes the SimpleMDE editor not to render
This reverts commit 752aa84ecc7c10c3e748e4f9c8f54f1f020dce04.
> Revert "Update django from 4.2.11 to 5.0.4"

- tcms/issuetracker/base.py
- tcms/issuetracker/tests/test_jira.py
- tcms/issuetracker/types.py
text will be truncated to 30k chars for automated POST requests and 6k chars for fallback GET requests to fit inside Jira limitations.
Otherwise you may see 400, 414 and/or 500 errors!
> Truncate TestCase.text length for Jira 1-click bug reports

- tcms/testplans/static/testplans/js/get.js
Fixes #3163
when viewing a test plan which is part of a tree structure all of its parents appear expended by default and the current TP is highlighted on the page. This commit adjusts the direction of the existing angle brackets icons to relfect this state and makes icons for parent test plans to point down, instead of right!
> Adjust angle bracket icon direction when viewing nested testplans

- etc/nginx.conf
- tcms/core/middleware.py
- tcms/templates/base.html
- tcms/templates/include/ads.html
- tests/test_http.sh
- tests/ui/test_upload_file.robot
- EthicalAds is a GDPR-compliant ad network for devs
- No cookie banners, and only dev-focused ads.
> Enable EthicalAds

- tcms/kiwi_auth/tests/test_views.py
b/c invited users may not know that
> Assert that password reset email contains username reminder

- tcms/testplans/static/testplans/js/get.js
the boolean expression tc[filterBy] was intended to check whether the requested field exists, as a way to avoid crashes in the case where we may have forgotten to update the code. However in the case when trying to search for manual test cases the raw value of this field is `false` which caused the entire expression to be evaulated as False and did not apply the filter.
> Update filter logic for Automated=False. Fixes #3841

- .github/workflows/coverity_scan.yml
- .github/workflows/lint.yml
- .github/workflows/sanity.yml
- .github/workflows/security.yml
- .github/workflows/testing.yml
- Dockerfile.buildroot
- tcms/package-lock.json
> Start using Node.js v22 inside container

- tcms/core/context_processors.py
- tcms/templates/base.html
- tcms/templates/include/ads.html
- tcms/templates/registration/password_reset_form.html
- tcms/testcases/templates/testcases/search.html
instead of the entire request contents. Otherwise this leads to traceback recursion in edge cases, for example when Kiwi TCMS is handling an error!
> Refactor request_contents_processor() to expose only data we use

- etc/nginx.conf
- tcms/core/middleware.py
- tests/test_http.sh
b/c we're loading an image, not a script and this isn't needed for now
> Revert change to CSP header

- tcms/telemetry/static/telemetry/js/testing/execution-dashboard.js
for TestCase.filter() and TestRun.filter() API calls on Execution Dashboard page
> Remove duplicate IDs to minimize size of WHERE clause

- tcms/telemetry/static/telemetry/js/testing/execution-dashboard.js
- tcms/telemetry/templates/telemetry/testing/execution-dashboard.html
These changes added two additional columns to the execution dashboard. A product column for the product associated with the test run and a component column which lists all the components associated to the test case.
> Update execution dashboard

- tcms/rpc/tests/test_testcase.py
- tcms/rpc/tests/test_testplan.py
- tcms/rpc/tests/test_testrun.py
- tcms/rpc/tests/utils.py
as documented for the tcms-api package instead of internal classes whose implementation may change. The public interface also provides a workaround for SSL issues which sometimes present themselves when we have long running workflows (not present in the API test suite ATM).
> Refactor: use the public interface tcms_api.TCMS().exec in tests
